// Image-variant manifest. Maintained by hand. Add new entries when we add new images.
//
// Bases that have -1280.webp variants generated by scripts/optimize-images.js
const HAS_1280 = new Set([
  "/images/dj-kevin-froger-bruiloft-scaled",
  "/images/dj-kevin-froger-apreskifeest",
  "/images/dj-kevin-froger-bedrijfsfeest",
  "/images/dj-booth-black",
  "/images/dj-booth-wit-design",
  "/images/dj-booth-apresski",
  "/images/dj-kevin-froger-prive-feest",
  "/images/dj-kevin-froger-bedrijfsfeest-lichtshow",
  "/images/kevin-portrait",
]);

// Subset that additionally has -1920.webp variants. Used for hero-style usage.
const HAS_1920 = new Set([
  "/images/dj-kevin-froger-bruiloft-scaled",
  "/images/dj-kevin-froger-prive-feest",
  "/images/dj-kevin-froger-bedrijfsfeest-lichtshow",
]);

export type ImageSources = { src: string; srcSet?: string };

/**
 * Build srcSet from a known image path. Returns the original path as src if
 * no variants are registered.
 */
export function responsiveImage(image: string): ImageSources {
  const m = image.match(/^(.+?)\.(jpeg|jpg|png|webp)$/i);
  if (!m) return { src: image };
  const base = m[1];
  if (!HAS_1280.has(base)) return { src: image };

  const sizes = ["640", "1280"];
  if (HAS_1920.has(base)) sizes.push("1920");

  return {
    src: `${base}-${sizes[sizes.length - 1]}.webp`,
    srcSet: sizes.map((s) => `${base}-${s}.webp ${s}w`).join(", "),
  };
}
