/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZakelijkDjRouteImport } from './routes/zakelijk-dj'
import { Route as WerkwijzeRouteImport } from './routes/werkwijze'
import { Route as VerjaardagDjRouteImport } from './routes/verjaardag-dj'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RegiosRouteImport } from './routes/regios'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrijzenRouteImport } from './routes/prijzen'
import { Route as FestivalDjRouteImport } from './routes/festival-dj'
import { Route as DjBoekenZwolleRouteImport } from './routes/dj-boeken-zwolle'
import { Route as DjBoekenZoetermeerRouteImport } from './routes/dj-boeken-zoetermeer'
import { Route as DjBoekenZeistRouteImport } from './routes/dj-boeken-zeist'
import { Route as DjBoekenZaltbommelRouteImport } from './routes/dj-boeken-zaltbommel'
import { Route as DjBoekenWageningenRouteImport } from './routes/dj-boeken-wageningen'
import { Route as DjBoekenVenloRouteImport } from './routes/dj-boeken-venlo'
import { Route as DjBoekenVeenendaalRouteImport } from './routes/dj-boeken-veenendaal'
import { Route as DjBoekenVarikRouteImport } from './routes/dj-boeken-varik'
import { Route as DjBoekenUtrechtRouteImport } from './routes/dj-boeken-utrecht'
import { Route as DjBoekenTuilRouteImport } from './routes/dj-boeken-tuil'
import { Route as DjBoekenTilburgRouteImport } from './routes/dj-boeken-tilburg'
import { Route as DjBoekenTielRouteImport } from './routes/dj-boeken-tiel'
import { Route as DjBoekenSpijkenisseRouteImport } from './routes/dj-boeken-spijkenisse'
import { Route as DjBoekenSchiedamRouteImport } from './routes/dj-boeken-schiedam'
import { Route as DjBoekenRotterdamRouteImport } from './routes/dj-boeken-rotterdam'
import { Route as DjBoekenRoermondRouteImport } from './routes/dj-boeken-roermond'
import { Route as DjBoekenOssRouteImport } from './routes/dj-boeken-oss'
import { Route as DjBoekenOphemertRouteImport } from './routes/dj-boeken-ophemert'
import { Route as DjBoekenNijmegenRouteImport } from './routes/dj-boeken-nijmegen'
import { Route as DjBoekenNieuwegeinRouteImport } from './routes/dj-boeken-nieuwegein'
import { Route as DjBoekenMiddelburgRouteImport } from './routes/dj-boeken-middelburg'
import { Route as DjBoekenMaastrichtRouteImport } from './routes/dj-boeken-maastricht'
import { Route as DjBoekenLeidenRouteImport } from './routes/dj-boeken-leiden'
import { Route as DjBoekenLeeuwardenRouteImport } from './routes/dj-boeken-leeuwarden'
import { Route as DjBoekenHoutenRouteImport } from './routes/dj-boeken-houten'
import { Route as DjBoekenHoekscheWaardRouteImport } from './routes/dj-boeken-hoeksche-waard'
import { Route as DjBoekenHilversumRouteImport } from './routes/dj-boeken-hilversum'
import { Route as DjBoekenHelmondRouteImport } from './routes/dj-boeken-helmond'
import { Route as DjBoekenHaarlemRouteImport } from './routes/dj-boeken-haarlem'
import { Route as DjBoekenGroningenRouteImport } from './routes/dj-boeken-groningen'
import { Route as DjBoekenGoudaRouteImport } from './routes/dj-boeken-gouda'
import { Route as DjBoekenGorinchemRouteImport } from './routes/dj-boeken-gorinchem'
import { Route as DjBoekenGeldermalsenRouteImport } from './routes/dj-boeken-geldermalsen'
import { Route as DjBoekenEnschedeRouteImport } from './routes/dj-boeken-enschede'
import { Route as DjBoekenEindhovenRouteImport } from './routes/dj-boeken-eindhoven'
import { Route as DjBoekenEdeRouteImport } from './routes/dj-boeken-ede'
import { Route as DjBoekenDordrechtRouteImport } from './routes/dj-boeken-dordrecht'
import { Route as DjBoekenDeventerRouteImport } from './routes/dj-boeken-deventer'
import { Route as DjBoekenDenHaagRouteImport } from './routes/dj-boeken-den-haag'
import { Route as DjBoekenDenBoschRouteImport } from './routes/dj-boeken-den-bosch'
import { Route as DjBoekenDelftRouteImport } from './routes/dj-boeken-delft'
import { Route as DjBoekenCulemborgRouteImport } from './routes/dj-boeken-culemborg'
import { Route as DjBoekenBredaRouteImport } from './routes/dj-boeken-breda'
import { Route as DjBoekenBetuweRouteImport } from './routes/dj-boeken-betuwe'
import { Route as DjBoekenAssenRouteImport } from './routes/dj-boeken-assen'
import { Route as DjBoekenArnhemRouteImport } from './routes/dj-boeken-arnhem'
import { Route as DjBoekenApeldoornRouteImport } from './routes/dj-boeken-apeldoorn'
import { Route as DjBoekenAmsterdamRouteImport } from './routes/dj-boeken-amsterdam'
import { Route as DjBoekenAmersfoortRouteImport } from './routes/dj-boeken-amersfoort'
import { Route as DjBoekenAlmereRouteImport } from './routes/dj-boeken-almere'
import { Route as DjBoekenAlkmaarRouteImport } from './routes/dj-boeken-alkmaar'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BruiloftDjRouteImport } from './routes/bruiloft-dj'
import { Route as BiografieRouteImport } from './routes/biografie'
import { Route as AlgemeneVoorwaardenRouteImport } from './routes/algemene-voorwaarden'
import { Route as IndexRouteImport } from './routes/index'

const ZakelijkDjRoute = ZakelijkDjRouteImport.update({
  id: '/zakelijk-dj',
  path: '/zakelijk-dj',
  getParentRoute: () => rootRouteImport,
} as any)
const WerkwijzeRoute = WerkwijzeRouteImport.update({
  id: '/werkwijze',
  path: '/werkwijze',
  getParentRoute: () => rootRouteImport,
} as any)
const VerjaardagDjRoute = VerjaardagDjRouteImport.update({
  id: '/verjaardag-dj',
  path: '/verjaardag-dj',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RegiosRoute = RegiosRouteImport.update({
  id: '/regios',
  path: '/regios',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrijzenRoute = PrijzenRouteImport.update({
  id: '/prijzen',
  path: '/prijzen',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalDjRoute = FestivalDjRouteImport.update({
  id: '/festival-dj',
  path: '/festival-dj',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenZwolleRoute = DjBoekenZwolleRouteImport.update({
  id: '/dj-boeken-zwolle',
  path: '/dj-boeken-zwolle',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenZoetermeerRoute = DjBoekenZoetermeerRouteImport.update({
  id: '/dj-boeken-zoetermeer',
  path: '/dj-boeken-zoetermeer',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenZeistRoute = DjBoekenZeistRouteImport.update({
  id: '/dj-boeken-zeist',
  path: '/dj-boeken-zeist',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenZaltbommelRoute = DjBoekenZaltbommelRouteImport.update({
  id: '/dj-boeken-zaltbommel',
  path: '/dj-boeken-zaltbommel',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenWageningenRoute = DjBoekenWageningenRouteImport.update({
  id: '/dj-boeken-wageningen',
  path: '/dj-boeken-wageningen',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenVenloRoute = DjBoekenVenloRouteImport.update({
  id: '/dj-boeken-venlo',
  path: '/dj-boeken-venlo',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenVeenendaalRoute = DjBoekenVeenendaalRouteImport.update({
  id: '/dj-boeken-veenendaal',
  path: '/dj-boeken-veenendaal',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenVarikRoute = DjBoekenVarikRouteImport.update({
  id: '/dj-boeken-varik',
  path: '/dj-boeken-varik',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenUtrechtRoute = DjBoekenUtrechtRouteImport.update({
  id: '/dj-boeken-utrecht',
  path: '/dj-boeken-utrecht',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenTuilRoute = DjBoekenTuilRouteImport.update({
  id: '/dj-boeken-tuil',
  path: '/dj-boeken-tuil',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenTilburgRoute = DjBoekenTilburgRouteImport.update({
  id: '/dj-boeken-tilburg',
  path: '/dj-boeken-tilburg',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenTielRoute = DjBoekenTielRouteImport.update({
  id: '/dj-boeken-tiel',
  path: '/dj-boeken-tiel',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenSpijkenisseRoute = DjBoekenSpijkenisseRouteImport.update({
  id: '/dj-boeken-spijkenisse',
  path: '/dj-boeken-spijkenisse',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenSchiedamRoute = DjBoekenSchiedamRouteImport.update({
  id: '/dj-boeken-schiedam',
  path: '/dj-boeken-schiedam',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenRotterdamRoute = DjBoekenRotterdamRouteImport.update({
  id: '/dj-boeken-rotterdam',
  path: '/dj-boeken-rotterdam',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenRoermondRoute = DjBoekenRoermondRouteImport.update({
  id: '/dj-boeken-roermond',
  path: '/dj-boeken-roermond',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenOssRoute = DjBoekenOssRouteImport.update({
  id: '/dj-boeken-oss',
  path: '/dj-boeken-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenOphemertRoute = DjBoekenOphemertRouteImport.update({
  id: '/dj-boeken-ophemert',
  path: '/dj-boeken-ophemert',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenNijmegenRoute = DjBoekenNijmegenRouteImport.update({
  id: '/dj-boeken-nijmegen',
  path: '/dj-boeken-nijmegen',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenNieuwegeinRoute = DjBoekenNieuwegeinRouteImport.update({
  id: '/dj-boeken-nieuwegein',
  path: '/dj-boeken-nieuwegein',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenMiddelburgRoute = DjBoekenMiddelburgRouteImport.update({
  id: '/dj-boeken-middelburg',
  path: '/dj-boeken-middelburg',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenMaastrichtRoute = DjBoekenMaastrichtRouteImport.update({
  id: '/dj-boeken-maastricht',
  path: '/dj-boeken-maastricht',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenLeidenRoute = DjBoekenLeidenRouteImport.update({
  id: '/dj-boeken-leiden',
  path: '/dj-boeken-leiden',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenLeeuwardenRoute = DjBoekenLeeuwardenRouteImport.update({
  id: '/dj-boeken-leeuwarden',
  path: '/dj-boeken-leeuwarden',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenHoutenRoute = DjBoekenHoutenRouteImport.update({
  id: '/dj-boeken-houten',
  path: '/dj-boeken-houten',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenHoekscheWaardRoute = DjBoekenHoekscheWaardRouteImport.update({
  id: '/dj-boeken-hoeksche-waard',
  path: '/dj-boeken-hoeksche-waard',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenHilversumRoute = DjBoekenHilversumRouteImport.update({
  id: '/dj-boeken-hilversum',
  path: '/dj-boeken-hilversum',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenHelmondRoute = DjBoekenHelmondRouteImport.update({
  id: '/dj-boeken-helmond',
  path: '/dj-boeken-helmond',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenHaarlemRoute = DjBoekenHaarlemRouteImport.update({
  id: '/dj-boeken-haarlem',
  path: '/dj-boeken-haarlem',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenGroningenRoute = DjBoekenGroningenRouteImport.update({
  id: '/dj-boeken-groningen',
  path: '/dj-boeken-groningen',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenGoudaRoute = DjBoekenGoudaRouteImport.update({
  id: '/dj-boeken-gouda',
  path: '/dj-boeken-gouda',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenGorinchemRoute = DjBoekenGorinchemRouteImport.update({
  id: '/dj-boeken-gorinchem',
  path: '/dj-boeken-gorinchem',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenGeldermalsenRoute = DjBoekenGeldermalsenRouteImport.update({
  id: '/dj-boeken-geldermalsen',
  path: '/dj-boeken-geldermalsen',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenEnschedeRoute = DjBoekenEnschedeRouteImport.update({
  id: '/dj-boeken-enschede',
  path: '/dj-boeken-enschede',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenEindhovenRoute = DjBoekenEindhovenRouteImport.update({
  id: '/dj-boeken-eindhoven',
  path: '/dj-boeken-eindhoven',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenEdeRoute = DjBoekenEdeRouteImport.update({
  id: '/dj-boeken-ede',
  path: '/dj-boeken-ede',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenDordrechtRoute = DjBoekenDordrechtRouteImport.update({
  id: '/dj-boeken-dordrecht',
  path: '/dj-boeken-dordrecht',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenDeventerRoute = DjBoekenDeventerRouteImport.update({
  id: '/dj-boeken-deventer',
  path: '/dj-boeken-deventer',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenDenHaagRoute = DjBoekenDenHaagRouteImport.update({
  id: '/dj-boeken-den-haag',
  path: '/dj-boeken-den-haag',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenDenBoschRoute = DjBoekenDenBoschRouteImport.update({
  id: '/dj-boeken-den-bosch',
  path: '/dj-boeken-den-bosch',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenDelftRoute = DjBoekenDelftRouteImport.update({
  id: '/dj-boeken-delft',
  path: '/dj-boeken-delft',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenCulemborgRoute = DjBoekenCulemborgRouteImport.update({
  id: '/dj-boeken-culemborg',
  path: '/dj-boeken-culemborg',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenBredaRoute = DjBoekenBredaRouteImport.update({
  id: '/dj-boeken-breda',
  path: '/dj-boeken-breda',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenBetuweRoute = DjBoekenBetuweRouteImport.update({
  id: '/dj-boeken-betuwe',
  path: '/dj-boeken-betuwe',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenAssenRoute = DjBoekenAssenRouteImport.update({
  id: '/dj-boeken-assen',
  path: '/dj-boeken-assen',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenArnhemRoute = DjBoekenArnhemRouteImport.update({
  id: '/dj-boeken-arnhem',
  path: '/dj-boeken-arnhem',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenApeldoornRoute = DjBoekenApeldoornRouteImport.update({
  id: '/dj-boeken-apeldoorn',
  path: '/dj-boeken-apeldoorn',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenAmsterdamRoute = DjBoekenAmsterdamRouteImport.update({
  id: '/dj-boeken-amsterdam',
  path: '/dj-boeken-amsterdam',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenAmersfoortRoute = DjBoekenAmersfoortRouteImport.update({
  id: '/dj-boeken-amersfoort',
  path: '/dj-boeken-amersfoort',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenAlmereRoute = DjBoekenAlmereRouteImport.update({
  id: '/dj-boeken-almere',
  path: '/dj-boeken-almere',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenAlkmaarRoute = DjBoekenAlkmaarRouteImport.update({
  id: '/dj-boeken-alkmaar',
  path: '/dj-boeken-alkmaar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BruiloftDjRoute = BruiloftDjRouteImport.update({
  id: '/bruiloft-dj',
  path: '/bruiloft-dj',
  getParentRoute: () => rootRouteImport,
} as any)
const BiografieRoute = BiografieRouteImport.update({
  id: '/biografie',
  path: '/biografie',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgemeneVoorwaardenRoute = AlgemeneVoorwaardenRouteImport.update({
  id: '/algemene-voorwaarden',
  path: '/algemene-voorwaarden',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/biografie': typeof BiografieRoute
  '/bruiloft-dj': typeof BruiloftDjRoute
  '/contact': typeof ContactRoute
  '/dj-boeken-alkmaar': typeof DjBoekenAlkmaarRoute
  '/dj-boeken-almere': typeof DjBoekenAlmereRoute
  '/dj-boeken-amersfoort': typeof DjBoekenAmersfoortRoute
  '/dj-boeken-amsterdam': typeof DjBoekenAmsterdamRoute
  '/dj-boeken-apeldoorn': typeof DjBoekenApeldoornRoute
  '/dj-boeken-arnhem': typeof DjBoekenArnhemRoute
  '/dj-boeken-assen': typeof DjBoekenAssenRoute
  '/dj-boeken-betuwe': typeof DjBoekenBetuweRoute
  '/dj-boeken-breda': typeof DjBoekenBredaRoute
  '/dj-boeken-culemborg': typeof DjBoekenCulemborgRoute
  '/dj-boeken-delft': typeof DjBoekenDelftRoute
  '/dj-boeken-den-bosch': typeof DjBoekenDenBoschRoute
  '/dj-boeken-den-haag': typeof DjBoekenDenHaagRoute
  '/dj-boeken-deventer': typeof DjBoekenDeventerRoute
  '/dj-boeken-dordrecht': typeof DjBoekenDordrechtRoute
  '/dj-boeken-ede': typeof DjBoekenEdeRoute
  '/dj-boeken-eindhoven': typeof DjBoekenEindhovenRoute
  '/dj-boeken-enschede': typeof DjBoekenEnschedeRoute
  '/dj-boeken-geldermalsen': typeof DjBoekenGeldermalsenRoute
  '/dj-boeken-gorinchem': typeof DjBoekenGorinchemRoute
  '/dj-boeken-gouda': typeof DjBoekenGoudaRoute
  '/dj-boeken-groningen': typeof DjBoekenGroningenRoute
  '/dj-boeken-haarlem': typeof DjBoekenHaarlemRoute
  '/dj-boeken-helmond': typeof DjBoekenHelmondRoute
  '/dj-boeken-hilversum': typeof DjBoekenHilversumRoute
  '/dj-boeken-hoeksche-waard': typeof DjBoekenHoekscheWaardRoute
  '/dj-boeken-houten': typeof DjBoekenHoutenRoute
  '/dj-boeken-leeuwarden': typeof DjBoekenLeeuwardenRoute
  '/dj-boeken-leiden': typeof DjBoekenLeidenRoute
  '/dj-boeken-maastricht': typeof DjBoekenMaastrichtRoute
  '/dj-boeken-middelburg': typeof DjBoekenMiddelburgRoute
  '/dj-boeken-nieuwegein': typeof DjBoekenNieuwegeinRoute
  '/dj-boeken-nijmegen': typeof DjBoekenNijmegenRoute
  '/dj-boeken-ophemert': typeof DjBoekenOphemertRoute
  '/dj-boeken-oss': typeof DjBoekenOssRoute
  '/dj-boeken-roermond': typeof DjBoekenRoermondRoute
  '/dj-boeken-rotterdam': typeof DjBoekenRotterdamRoute
  '/dj-boeken-schiedam': typeof DjBoekenSchiedamRoute
  '/dj-boeken-spijkenisse': typeof DjBoekenSpijkenisseRoute
  '/dj-boeken-tiel': typeof DjBoekenTielRoute
  '/dj-boeken-tilburg': typeof DjBoekenTilburgRoute
  '/dj-boeken-tuil': typeof DjBoekenTuilRoute
  '/dj-boeken-utrecht': typeof DjBoekenUtrechtRoute
  '/dj-boeken-varik': typeof DjBoekenVarikRoute
  '/dj-boeken-veenendaal': typeof DjBoekenVeenendaalRoute
  '/dj-boeken-venlo': typeof DjBoekenVenloRoute
  '/dj-boeken-wageningen': typeof DjBoekenWageningenRoute
  '/dj-boeken-zaltbommel': typeof DjBoekenZaltbommelRoute
  '/dj-boeken-zeist': typeof DjBoekenZeistRoute
  '/dj-boeken-zoetermeer': typeof DjBoekenZoetermeerRoute
  '/dj-boeken-zwolle': typeof DjBoekenZwolleRoute
  '/festival-dj': typeof FestivalDjRoute
  '/prijzen': typeof PrijzenRoute
  '/privacy': typeof PrivacyRoute
  '/regios': typeof RegiosRoute
  '/reviews': typeof ReviewsRoute
  '/verjaardag-dj': typeof VerjaardagDjRoute
  '/werkwijze': typeof WerkwijzeRoute
  '/zakelijk-dj': typeof ZakelijkDjRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/biografie': typeof BiografieRoute
  '/bruiloft-dj': typeof BruiloftDjRoute
  '/contact': typeof ContactRoute
  '/dj-boeken-alkmaar': typeof DjBoekenAlkmaarRoute
  '/dj-boeken-almere': typeof DjBoekenAlmereRoute
  '/dj-boeken-amersfoort': typeof DjBoekenAmersfoortRoute
  '/dj-boeken-amsterdam': typeof DjBoekenAmsterdamRoute
  '/dj-boeken-apeldoorn': typeof DjBoekenApeldoornRoute
  '/dj-boeken-arnhem': typeof DjBoekenArnhemRoute
  '/dj-boeken-assen': typeof DjBoekenAssenRoute
  '/dj-boeken-betuwe': typeof DjBoekenBetuweRoute
  '/dj-boeken-breda': typeof DjBoekenBredaRoute
  '/dj-boeken-culemborg': typeof DjBoekenCulemborgRoute
  '/dj-boeken-delft': typeof DjBoekenDelftRoute
  '/dj-boeken-den-bosch': typeof DjBoekenDenBoschRoute
  '/dj-boeken-den-haag': typeof DjBoekenDenHaagRoute
  '/dj-boeken-deventer': typeof DjBoekenDeventerRoute
  '/dj-boeken-dordrecht': typeof DjBoekenDordrechtRoute
  '/dj-boeken-ede': typeof DjBoekenEdeRoute
  '/dj-boeken-eindhoven': typeof DjBoekenEindhovenRoute
  '/dj-boeken-enschede': typeof DjBoekenEnschedeRoute
  '/dj-boeken-geldermalsen': typeof DjBoekenGeldermalsenRoute
  '/dj-boeken-gorinchem': typeof DjBoekenGorinchemRoute
  '/dj-boeken-gouda': typeof DjBoekenGoudaRoute
  '/dj-boeken-groningen': typeof DjBoekenGroningenRoute
  '/dj-boeken-haarlem': typeof DjBoekenHaarlemRoute
  '/dj-boeken-helmond': typeof DjBoekenHelmondRoute
  '/dj-boeken-hilversum': typeof DjBoekenHilversumRoute
  '/dj-boeken-hoeksche-waard': typeof DjBoekenHoekscheWaardRoute
  '/dj-boeken-houten': typeof DjBoekenHoutenRoute
  '/dj-boeken-leeuwarden': typeof DjBoekenLeeuwardenRoute
  '/dj-boeken-leiden': typeof DjBoekenLeidenRoute
  '/dj-boeken-maastricht': typeof DjBoekenMaastrichtRoute
  '/dj-boeken-middelburg': typeof DjBoekenMiddelburgRoute
  '/dj-boeken-nieuwegein': typeof DjBoekenNieuwegeinRoute
  '/dj-boeken-nijmegen': typeof DjBoekenNijmegenRoute
  '/dj-boeken-ophemert': typeof DjBoekenOphemertRoute
  '/dj-boeken-oss': typeof DjBoekenOssRoute
  '/dj-boeken-roermond': typeof DjBoekenRoermondRoute
  '/dj-boeken-rotterdam': typeof DjBoekenRotterdamRoute
  '/dj-boeken-schiedam': typeof DjBoekenSchiedamRoute
  '/dj-boeken-spijkenisse': typeof DjBoekenSpijkenisseRoute
  '/dj-boeken-tiel': typeof DjBoekenTielRoute
  '/dj-boeken-tilburg': typeof DjBoekenTilburgRoute
  '/dj-boeken-tuil': typeof DjBoekenTuilRoute
  '/dj-boeken-utrecht': typeof DjBoekenUtrechtRoute
  '/dj-boeken-varik': typeof DjBoekenVarikRoute
  '/dj-boeken-veenendaal': typeof DjBoekenVeenendaalRoute
  '/dj-boeken-venlo': typeof DjBoekenVenloRoute
  '/dj-boeken-wageningen': typeof DjBoekenWageningenRoute
  '/dj-boeken-zaltbommel': typeof DjBoekenZaltbommelRoute
  '/dj-boeken-zeist': typeof DjBoekenZeistRoute
  '/dj-boeken-zoetermeer': typeof DjBoekenZoetermeerRoute
  '/dj-boeken-zwolle': typeof DjBoekenZwolleRoute
  '/festival-dj': typeof FestivalDjRoute
  '/prijzen': typeof PrijzenRoute
  '/privacy': typeof PrivacyRoute
  '/regios': typeof RegiosRoute
  '/reviews': typeof ReviewsRoute
  '/verjaardag-dj': typeof VerjaardagDjRoute
  '/werkwijze': typeof WerkwijzeRoute
  '/zakelijk-dj': typeof ZakelijkDjRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/biografie': typeof BiografieRoute
  '/bruiloft-dj': typeof BruiloftDjRoute
  '/contact': typeof ContactRoute
  '/dj-boeken-alkmaar': typeof DjBoekenAlkmaarRoute
  '/dj-boeken-almere': typeof DjBoekenAlmereRoute
  '/dj-boeken-amersfoort': typeof DjBoekenAmersfoortRoute
  '/dj-boeken-amsterdam': typeof DjBoekenAmsterdamRoute
  '/dj-boeken-apeldoorn': typeof DjBoekenApeldoornRoute
  '/dj-boeken-arnhem': typeof DjBoekenArnhemRoute
  '/dj-boeken-assen': typeof DjBoekenAssenRoute
  '/dj-boeken-betuwe': typeof DjBoekenBetuweRoute
  '/dj-boeken-breda': typeof DjBoekenBredaRoute
  '/dj-boeken-culemborg': typeof DjBoekenCulemborgRoute
  '/dj-boeken-delft': typeof DjBoekenDelftRoute
  '/dj-boeken-den-bosch': typeof DjBoekenDenBoschRoute
  '/dj-boeken-den-haag': typeof DjBoekenDenHaagRoute
  '/dj-boeken-deventer': typeof DjBoekenDeventerRoute
  '/dj-boeken-dordrecht': typeof DjBoekenDordrechtRoute
  '/dj-boeken-ede': typeof DjBoekenEdeRoute
  '/dj-boeken-eindhoven': typeof DjBoekenEindhovenRoute
  '/dj-boeken-enschede': typeof DjBoekenEnschedeRoute
  '/dj-boeken-geldermalsen': typeof DjBoekenGeldermalsenRoute
  '/dj-boeken-gorinchem': typeof DjBoekenGorinchemRoute
  '/dj-boeken-gouda': typeof DjBoekenGoudaRoute
  '/dj-boeken-groningen': typeof DjBoekenGroningenRoute
  '/dj-boeken-haarlem': typeof DjBoekenHaarlemRoute
  '/dj-boeken-helmond': typeof DjBoekenHelmondRoute
  '/dj-boeken-hilversum': typeof DjBoekenHilversumRoute
  '/dj-boeken-hoeksche-waard': typeof DjBoekenHoekscheWaardRoute
  '/dj-boeken-houten': typeof DjBoekenHoutenRoute
  '/dj-boeken-leeuwarden': typeof DjBoekenLeeuwardenRoute
  '/dj-boeken-leiden': typeof DjBoekenLeidenRoute
  '/dj-boeken-maastricht': typeof DjBoekenMaastrichtRoute
  '/dj-boeken-middelburg': typeof DjBoekenMiddelburgRoute
  '/dj-boeken-nieuwegein': typeof DjBoekenNieuwegeinRoute
  '/dj-boeken-nijmegen': typeof DjBoekenNijmegenRoute
  '/dj-boeken-ophemert': typeof DjBoekenOphemertRoute
  '/dj-boeken-oss': typeof DjBoekenOssRoute
  '/dj-boeken-roermond': typeof DjBoekenRoermondRoute
  '/dj-boeken-rotterdam': typeof DjBoekenRotterdamRoute
  '/dj-boeken-schiedam': typeof DjBoekenSchiedamRoute
  '/dj-boeken-spijkenisse': typeof DjBoekenSpijkenisseRoute
  '/dj-boeken-tiel': typeof DjBoekenTielRoute
  '/dj-boeken-tilburg': typeof DjBoekenTilburgRoute
  '/dj-boeken-tuil': typeof DjBoekenTuilRoute
  '/dj-boeken-utrecht': typeof DjBoekenUtrechtRoute
  '/dj-boeken-varik': typeof DjBoekenVarikRoute
  '/dj-boeken-veenendaal': typeof DjBoekenVeenendaalRoute
  '/dj-boeken-venlo': typeof DjBoekenVenloRoute
  '/dj-boeken-wageningen': typeof DjBoekenWageningenRoute
  '/dj-boeken-zaltbommel': typeof DjBoekenZaltbommelRoute
  '/dj-boeken-zeist': typeof DjBoekenZeistRoute
  '/dj-boeken-zoetermeer': typeof DjBoekenZoetermeerRoute
  '/dj-boeken-zwolle': typeof DjBoekenZwolleRoute
  '/festival-dj': typeof FestivalDjRoute
  '/prijzen': typeof PrijzenRoute
  '/privacy': typeof PrivacyRoute
  '/regios': typeof RegiosRoute
  '/reviews': typeof ReviewsRoute
  '/verjaardag-dj': typeof VerjaardagDjRoute
  '/werkwijze': typeof WerkwijzeRoute
  '/zakelijk-dj': typeof ZakelijkDjRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/algemene-voorwaarden'
    | '/biografie'
    | '/bruiloft-dj'
    | '/contact'
    | '/dj-boeken-alkmaar'
    | '/dj-boeken-almere'
    | '/dj-boeken-amersfoort'
    | '/dj-boeken-amsterdam'
    | '/dj-boeken-apeldoorn'
    | '/dj-boeken-arnhem'
    | '/dj-boeken-assen'
    | '/dj-boeken-betuwe'
    | '/dj-boeken-breda'
    | '/dj-boeken-culemborg'
    | '/dj-boeken-delft'
    | '/dj-boeken-den-bosch'
    | '/dj-boeken-den-haag'
    | '/dj-boeken-deventer'
    | '/dj-boeken-dordrecht'
    | '/dj-boeken-ede'
    | '/dj-boeken-eindhoven'
    | '/dj-boeken-enschede'
    | '/dj-boeken-geldermalsen'
    | '/dj-boeken-gorinchem'
    | '/dj-boeken-gouda'
    | '/dj-boeken-groningen'
    | '/dj-boeken-haarlem'
    | '/dj-boeken-helmond'
    | '/dj-boeken-hilversum'
    | '/dj-boeken-hoeksche-waard'
    | '/dj-boeken-houten'
    | '/dj-boeken-leeuwarden'
    | '/dj-boeken-leiden'
    | '/dj-boeken-maastricht'
    | '/dj-boeken-middelburg'
    | '/dj-boeken-nieuwegein'
    | '/dj-boeken-nijmegen'
    | '/dj-boeken-ophemert'
    | '/dj-boeken-oss'
    | '/dj-boeken-roermond'
    | '/dj-boeken-rotterdam'
    | '/dj-boeken-schiedam'
    | '/dj-boeken-spijkenisse'
    | '/dj-boeken-tiel'
    | '/dj-boeken-tilburg'
    | '/dj-boeken-tuil'
    | '/dj-boeken-utrecht'
    | '/dj-boeken-varik'
    | '/dj-boeken-veenendaal'
    | '/dj-boeken-venlo'
    | '/dj-boeken-wageningen'
    | '/dj-boeken-zaltbommel'
    | '/dj-boeken-zeist'
    | '/dj-boeken-zoetermeer'
    | '/dj-boeken-zwolle'
    | '/festival-dj'
    | '/prijzen'
    | '/privacy'
    | '/regios'
    | '/reviews'
    | '/verjaardag-dj'
    | '/werkwijze'
    | '/zakelijk-dj'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/algemene-voorwaarden'
    | '/biografie'
    | '/bruiloft-dj'
    | '/contact'
    | '/dj-boeken-alkmaar'
    | '/dj-boeken-almere'
    | '/dj-boeken-amersfoort'
    | '/dj-boeken-amsterdam'
    | '/dj-boeken-apeldoorn'
    | '/dj-boeken-arnhem'
    | '/dj-boeken-assen'
    | '/dj-boeken-betuwe'
    | '/dj-boeken-breda'
    | '/dj-boeken-culemborg'
    | '/dj-boeken-delft'
    | '/dj-boeken-den-bosch'
    | '/dj-boeken-den-haag'
    | '/dj-boeken-deventer'
    | '/dj-boeken-dordrecht'
    | '/dj-boeken-ede'
    | '/dj-boeken-eindhoven'
    | '/dj-boeken-enschede'
    | '/dj-boeken-geldermalsen'
    | '/dj-boeken-gorinchem'
    | '/dj-boeken-gouda'
    | '/dj-boeken-groningen'
    | '/dj-boeken-haarlem'
    | '/dj-boeken-helmond'
    | '/dj-boeken-hilversum'
    | '/dj-boeken-hoeksche-waard'
    | '/dj-boeken-houten'
    | '/dj-boeken-leeuwarden'
    | '/dj-boeken-leiden'
    | '/dj-boeken-maastricht'
    | '/dj-boeken-middelburg'
    | '/dj-boeken-nieuwegein'
    | '/dj-boeken-nijmegen'
    | '/dj-boeken-ophemert'
    | '/dj-boeken-oss'
    | '/dj-boeken-roermond'
    | '/dj-boeken-rotterdam'
    | '/dj-boeken-schiedam'
    | '/dj-boeken-spijkenisse'
    | '/dj-boeken-tiel'
    | '/dj-boeken-tilburg'
    | '/dj-boeken-tuil'
    | '/dj-boeken-utrecht'
    | '/dj-boeken-varik'
    | '/dj-boeken-veenendaal'
    | '/dj-boeken-venlo'
    | '/dj-boeken-wageningen'
    | '/dj-boeken-zaltbommel'
    | '/dj-boeken-zeist'
    | '/dj-boeken-zoetermeer'
    | '/dj-boeken-zwolle'
    | '/festival-dj'
    | '/prijzen'
    | '/privacy'
    | '/regios'
    | '/reviews'
    | '/verjaardag-dj'
    | '/werkwijze'
    | '/zakelijk-dj'
  id:
    | '__root__'
    | '/'
    | '/algemene-voorwaarden'
    | '/biografie'
    | '/bruiloft-dj'
    | '/contact'
    | '/dj-boeken-alkmaar'
    | '/dj-boeken-almere'
    | '/dj-boeken-amersfoort'
    | '/dj-boeken-amsterdam'
    | '/dj-boeken-apeldoorn'
    | '/dj-boeken-arnhem'
    | '/dj-boeken-assen'
    | '/dj-boeken-betuwe'
    | '/dj-boeken-breda'
    | '/dj-boeken-culemborg'
    | '/dj-boeken-delft'
    | '/dj-boeken-den-bosch'
    | '/dj-boeken-den-haag'
    | '/dj-boeken-deventer'
    | '/dj-boeken-dordrecht'
    | '/dj-boeken-ede'
    | '/dj-boeken-eindhoven'
    | '/dj-boeken-enschede'
    | '/dj-boeken-geldermalsen'
    | '/dj-boeken-gorinchem'
    | '/dj-boeken-gouda'
    | '/dj-boeken-groningen'
    | '/dj-boeken-haarlem'
    | '/dj-boeken-helmond'
    | '/dj-boeken-hilversum'
    | '/dj-boeken-hoeksche-waard'
    | '/dj-boeken-houten'
    | '/dj-boeken-leeuwarden'
    | '/dj-boeken-leiden'
    | '/dj-boeken-maastricht'
    | '/dj-boeken-middelburg'
    | '/dj-boeken-nieuwegein'
    | '/dj-boeken-nijmegen'
    | '/dj-boeken-ophemert'
    | '/dj-boeken-oss'
    | '/dj-boeken-roermond'
    | '/dj-boeken-rotterdam'
    | '/dj-boeken-schiedam'
    | '/dj-boeken-spijkenisse'
    | '/dj-boeken-tiel'
    | '/dj-boeken-tilburg'
    | '/dj-boeken-tuil'
    | '/dj-boeken-utrecht'
    | '/dj-boeken-varik'
    | '/dj-boeken-veenendaal'
    | '/dj-boeken-venlo'
    | '/dj-boeken-wageningen'
    | '/dj-boeken-zaltbommel'
    | '/dj-boeken-zeist'
    | '/dj-boeken-zoetermeer'
    | '/dj-boeken-zwolle'
    | '/festival-dj'
    | '/prijzen'
    | '/privacy'
    | '/regios'
    | '/reviews'
    | '/verjaardag-dj'
    | '/werkwijze'
    | '/zakelijk-dj'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlgemeneVoorwaardenRoute: typeof AlgemeneVoorwaardenRoute
  BiografieRoute: typeof BiografieRoute
  BruiloftDjRoute: typeof BruiloftDjRoute
  ContactRoute: typeof ContactRoute
  DjBoekenAlkmaarRoute: typeof DjBoekenAlkmaarRoute
  DjBoekenAlmereRoute: typeof DjBoekenAlmereRoute
  DjBoekenAmersfoortRoute: typeof DjBoekenAmersfoortRoute
  DjBoekenAmsterdamRoute: typeof DjBoekenAmsterdamRoute
  DjBoekenApeldoornRoute: typeof DjBoekenApeldoornRoute
  DjBoekenArnhemRoute: typeof DjBoekenArnhemRoute
  DjBoekenAssenRoute: typeof DjBoekenAssenRoute
  DjBoekenBetuweRoute: typeof DjBoekenBetuweRoute
  DjBoekenBredaRoute: typeof DjBoekenBredaRoute
  DjBoekenCulemborgRoute: typeof DjBoekenCulemborgRoute
  DjBoekenDelftRoute: typeof DjBoekenDelftRoute
  DjBoekenDenBoschRoute: typeof DjBoekenDenBoschRoute
  DjBoekenDenHaagRoute: typeof DjBoekenDenHaagRoute
  DjBoekenDeventerRoute: typeof DjBoekenDeventerRoute
  DjBoekenDordrechtRoute: typeof DjBoekenDordrechtRoute
  DjBoekenEdeRoute: typeof DjBoekenEdeRoute
  DjBoekenEindhovenRoute: typeof DjBoekenEindhovenRoute
  DjBoekenEnschedeRoute: typeof DjBoekenEnschedeRoute
  DjBoekenGeldermalsenRoute: typeof DjBoekenGeldermalsenRoute
  DjBoekenGorinchemRoute: typeof DjBoekenGorinchemRoute
  DjBoekenGoudaRoute: typeof DjBoekenGoudaRoute
  DjBoekenGroningenRoute: typeof DjBoekenGroningenRoute
  DjBoekenHaarlemRoute: typeof DjBoekenHaarlemRoute
  DjBoekenHelmondRoute: typeof DjBoekenHelmondRoute
  DjBoekenHilversumRoute: typeof DjBoekenHilversumRoute
  DjBoekenHoekscheWaardRoute: typeof DjBoekenHoekscheWaardRoute
  DjBoekenHoutenRoute: typeof DjBoekenHoutenRoute
  DjBoekenLeeuwardenRoute: typeof DjBoekenLeeuwardenRoute
  DjBoekenLeidenRoute: typeof DjBoekenLeidenRoute
  DjBoekenMaastrichtRoute: typeof DjBoekenMaastrichtRoute
  DjBoekenMiddelburgRoute: typeof DjBoekenMiddelburgRoute
  DjBoekenNieuwegeinRoute: typeof DjBoekenNieuwegeinRoute
  DjBoekenNijmegenRoute: typeof DjBoekenNijmegenRoute
  DjBoekenOphemertRoute: typeof DjBoekenOphemertRoute
  DjBoekenOssRoute: typeof DjBoekenOssRoute
  DjBoekenRoermondRoute: typeof DjBoekenRoermondRoute
  DjBoekenRotterdamRoute: typeof DjBoekenRotterdamRoute
  DjBoekenSchiedamRoute: typeof DjBoekenSchiedamRoute
  DjBoekenSpijkenisseRoute: typeof DjBoekenSpijkenisseRoute
  DjBoekenTielRoute: typeof DjBoekenTielRoute
  DjBoekenTilburgRoute: typeof DjBoekenTilburgRoute
  DjBoekenTuilRoute: typeof DjBoekenTuilRoute
  DjBoekenUtrechtRoute: typeof DjBoekenUtrechtRoute
  DjBoekenVarikRoute: typeof DjBoekenVarikRoute
  DjBoekenVeenendaalRoute: typeof DjBoekenVeenendaalRoute
  DjBoekenVenloRoute: typeof DjBoekenVenloRoute
  DjBoekenWageningenRoute: typeof DjBoekenWageningenRoute
  DjBoekenZaltbommelRoute: typeof DjBoekenZaltbommelRoute
  DjBoekenZeistRoute: typeof DjBoekenZeistRoute
  DjBoekenZoetermeerRoute: typeof DjBoekenZoetermeerRoute
  DjBoekenZwolleRoute: typeof DjBoekenZwolleRoute
  FestivalDjRoute: typeof FestivalDjRoute
  PrijzenRoute: typeof PrijzenRoute
  PrivacyRoute: typeof PrivacyRoute
  RegiosRoute: typeof RegiosRoute
  ReviewsRoute: typeof ReviewsRoute
  VerjaardagDjRoute: typeof VerjaardagDjRoute
  WerkwijzeRoute: typeof WerkwijzeRoute
  ZakelijkDjRoute: typeof ZakelijkDjRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zakelijk-dj': {
      id: '/zakelijk-dj'
      path: '/zakelijk-dj'
      fullPath: '/zakelijk-dj'
      preLoaderRoute: typeof ZakelijkDjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/werkwijze': {
      id: '/werkwijze'
      path: '/werkwijze'
      fullPath: '/werkwijze'
      preLoaderRoute: typeof WerkwijzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verjaardag-dj': {
      id: '/verjaardag-dj'
      path: '/verjaardag-dj'
      fullPath: '/verjaardag-dj'
      preLoaderRoute: typeof VerjaardagDjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regios': {
      id: '/regios'
      path: '/regios'
      fullPath: '/regios'
      preLoaderRoute: typeof RegiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prijzen': {
      id: '/prijzen'
      path: '/prijzen'
      fullPath: '/prijzen'
      preLoaderRoute: typeof PrijzenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festival-dj': {
      id: '/festival-dj'
      path: '/festival-dj'
      fullPath: '/festival-dj'
      preLoaderRoute: typeof FestivalDjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-zwolle': {
      id: '/dj-boeken-zwolle'
      path: '/dj-boeken-zwolle'
      fullPath: '/dj-boeken-zwolle'
      preLoaderRoute: typeof DjBoekenZwolleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-zoetermeer': {
      id: '/dj-boeken-zoetermeer'
      path: '/dj-boeken-zoetermeer'
      fullPath: '/dj-boeken-zoetermeer'
      preLoaderRoute: typeof DjBoekenZoetermeerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-zeist': {
      id: '/dj-boeken-zeist'
      path: '/dj-boeken-zeist'
      fullPath: '/dj-boeken-zeist'
      preLoaderRoute: typeof DjBoekenZeistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-zaltbommel': {
      id: '/dj-boeken-zaltbommel'
      path: '/dj-boeken-zaltbommel'
      fullPath: '/dj-boeken-zaltbommel'
      preLoaderRoute: typeof DjBoekenZaltbommelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-wageningen': {
      id: '/dj-boeken-wageningen'
      path: '/dj-boeken-wageningen'
      fullPath: '/dj-boeken-wageningen'
      preLoaderRoute: typeof DjBoekenWageningenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-venlo': {
      id: '/dj-boeken-venlo'
      path: '/dj-boeken-venlo'
      fullPath: '/dj-boeken-venlo'
      preLoaderRoute: typeof DjBoekenVenloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-veenendaal': {
      id: '/dj-boeken-veenendaal'
      path: '/dj-boeken-veenendaal'
      fullPath: '/dj-boeken-veenendaal'
      preLoaderRoute: typeof DjBoekenVeenendaalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-varik': {
      id: '/dj-boeken-varik'
      path: '/dj-boeken-varik'
      fullPath: '/dj-boeken-varik'
      preLoaderRoute: typeof DjBoekenVarikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-utrecht': {
      id: '/dj-boeken-utrecht'
      path: '/dj-boeken-utrecht'
      fullPath: '/dj-boeken-utrecht'
      preLoaderRoute: typeof DjBoekenUtrechtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-tuil': {
      id: '/dj-boeken-tuil'
      path: '/dj-boeken-tuil'
      fullPath: '/dj-boeken-tuil'
      preLoaderRoute: typeof DjBoekenTuilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-tilburg': {
      id: '/dj-boeken-tilburg'
      path: '/dj-boeken-tilburg'
      fullPath: '/dj-boeken-tilburg'
      preLoaderRoute: typeof DjBoekenTilburgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-tiel': {
      id: '/dj-boeken-tiel'
      path: '/dj-boeken-tiel'
      fullPath: '/dj-boeken-tiel'
      preLoaderRoute: typeof DjBoekenTielRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-spijkenisse': {
      id: '/dj-boeken-spijkenisse'
      path: '/dj-boeken-spijkenisse'
      fullPath: '/dj-boeken-spijkenisse'
      preLoaderRoute: typeof DjBoekenSpijkenisseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-schiedam': {
      id: '/dj-boeken-schiedam'
      path: '/dj-boeken-schiedam'
      fullPath: '/dj-boeken-schiedam'
      preLoaderRoute: typeof DjBoekenSchiedamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-rotterdam': {
      id: '/dj-boeken-rotterdam'
      path: '/dj-boeken-rotterdam'
      fullPath: '/dj-boeken-rotterdam'
      preLoaderRoute: typeof DjBoekenRotterdamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-roermond': {
      id: '/dj-boeken-roermond'
      path: '/dj-boeken-roermond'
      fullPath: '/dj-boeken-roermond'
      preLoaderRoute: typeof DjBoekenRoermondRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-oss': {
      id: '/dj-boeken-oss'
      path: '/dj-boeken-oss'
      fullPath: '/dj-boeken-oss'
      preLoaderRoute: typeof DjBoekenOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-ophemert': {
      id: '/dj-boeken-ophemert'
      path: '/dj-boeken-ophemert'
      fullPath: '/dj-boeken-ophemert'
      preLoaderRoute: typeof DjBoekenOphemertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-nijmegen': {
      id: '/dj-boeken-nijmegen'
      path: '/dj-boeken-nijmegen'
      fullPath: '/dj-boeken-nijmegen'
      preLoaderRoute: typeof DjBoekenNijmegenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-nieuwegein': {
      id: '/dj-boeken-nieuwegein'
      path: '/dj-boeken-nieuwegein'
      fullPath: '/dj-boeken-nieuwegein'
      preLoaderRoute: typeof DjBoekenNieuwegeinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-middelburg': {
      id: '/dj-boeken-middelburg'
      path: '/dj-boeken-middelburg'
      fullPath: '/dj-boeken-middelburg'
      preLoaderRoute: typeof DjBoekenMiddelburgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-maastricht': {
      id: '/dj-boeken-maastricht'
      path: '/dj-boeken-maastricht'
      fullPath: '/dj-boeken-maastricht'
      preLoaderRoute: typeof DjBoekenMaastrichtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-leiden': {
      id: '/dj-boeken-leiden'
      path: '/dj-boeken-leiden'
      fullPath: '/dj-boeken-leiden'
      preLoaderRoute: typeof DjBoekenLeidenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-leeuwarden': {
      id: '/dj-boeken-leeuwarden'
      path: '/dj-boeken-leeuwarden'
      fullPath: '/dj-boeken-leeuwarden'
      preLoaderRoute: typeof DjBoekenLeeuwardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-houten': {
      id: '/dj-boeken-houten'
      path: '/dj-boeken-houten'
      fullPath: '/dj-boeken-houten'
      preLoaderRoute: typeof DjBoekenHoutenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-hoeksche-waard': {
      id: '/dj-boeken-hoeksche-waard'
      path: '/dj-boeken-hoeksche-waard'
      fullPath: '/dj-boeken-hoeksche-waard'
      preLoaderRoute: typeof DjBoekenHoekscheWaardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-hilversum': {
      id: '/dj-boeken-hilversum'
      path: '/dj-boeken-hilversum'
      fullPath: '/dj-boeken-hilversum'
      preLoaderRoute: typeof DjBoekenHilversumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-helmond': {
      id: '/dj-boeken-helmond'
      path: '/dj-boeken-helmond'
      fullPath: '/dj-boeken-helmond'
      preLoaderRoute: typeof DjBoekenHelmondRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-haarlem': {
      id: '/dj-boeken-haarlem'
      path: '/dj-boeken-haarlem'
      fullPath: '/dj-boeken-haarlem'
      preLoaderRoute: typeof DjBoekenHaarlemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-groningen': {
      id: '/dj-boeken-groningen'
      path: '/dj-boeken-groningen'
      fullPath: '/dj-boeken-groningen'
      preLoaderRoute: typeof DjBoekenGroningenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-gouda': {
      id: '/dj-boeken-gouda'
      path: '/dj-boeken-gouda'
      fullPath: '/dj-boeken-gouda'
      preLoaderRoute: typeof DjBoekenGoudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-gorinchem': {
      id: '/dj-boeken-gorinchem'
      path: '/dj-boeken-gorinchem'
      fullPath: '/dj-boeken-gorinchem'
      preLoaderRoute: typeof DjBoekenGorinchemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-geldermalsen': {
      id: '/dj-boeken-geldermalsen'
      path: '/dj-boeken-geldermalsen'
      fullPath: '/dj-boeken-geldermalsen'
      preLoaderRoute: typeof DjBoekenGeldermalsenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-enschede': {
      id: '/dj-boeken-enschede'
      path: '/dj-boeken-enschede'
      fullPath: '/dj-boeken-enschede'
      preLoaderRoute: typeof DjBoekenEnschedeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-eindhoven': {
      id: '/dj-boeken-eindhoven'
      path: '/dj-boeken-eindhoven'
      fullPath: '/dj-boeken-eindhoven'
      preLoaderRoute: typeof DjBoekenEindhovenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-ede': {
      id: '/dj-boeken-ede'
      path: '/dj-boeken-ede'
      fullPath: '/dj-boeken-ede'
      preLoaderRoute: typeof DjBoekenEdeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-dordrecht': {
      id: '/dj-boeken-dordrecht'
      path: '/dj-boeken-dordrecht'
      fullPath: '/dj-boeken-dordrecht'
      preLoaderRoute: typeof DjBoekenDordrechtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-deventer': {
      id: '/dj-boeken-deventer'
      path: '/dj-boeken-deventer'
      fullPath: '/dj-boeken-deventer'
      preLoaderRoute: typeof DjBoekenDeventerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-den-haag': {
      id: '/dj-boeken-den-haag'
      path: '/dj-boeken-den-haag'
      fullPath: '/dj-boeken-den-haag'
      preLoaderRoute: typeof DjBoekenDenHaagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-den-bosch': {
      id: '/dj-boeken-den-bosch'
      path: '/dj-boeken-den-bosch'
      fullPath: '/dj-boeken-den-bosch'
      preLoaderRoute: typeof DjBoekenDenBoschRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-delft': {
      id: '/dj-boeken-delft'
      path: '/dj-boeken-delft'
      fullPath: '/dj-boeken-delft'
      preLoaderRoute: typeof DjBoekenDelftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-culemborg': {
      id: '/dj-boeken-culemborg'
      path: '/dj-boeken-culemborg'
      fullPath: '/dj-boeken-culemborg'
      preLoaderRoute: typeof DjBoekenCulemborgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-breda': {
      id: '/dj-boeken-breda'
      path: '/dj-boeken-breda'
      fullPath: '/dj-boeken-breda'
      preLoaderRoute: typeof DjBoekenBredaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-betuwe': {
      id: '/dj-boeken-betuwe'
      path: '/dj-boeken-betuwe'
      fullPath: '/dj-boeken-betuwe'
      preLoaderRoute: typeof DjBoekenBetuweRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-assen': {
      id: '/dj-boeken-assen'
      path: '/dj-boeken-assen'
      fullPath: '/dj-boeken-assen'
      preLoaderRoute: typeof DjBoekenAssenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-arnhem': {
      id: '/dj-boeken-arnhem'
      path: '/dj-boeken-arnhem'
      fullPath: '/dj-boeken-arnhem'
      preLoaderRoute: typeof DjBoekenArnhemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-apeldoorn': {
      id: '/dj-boeken-apeldoorn'
      path: '/dj-boeken-apeldoorn'
      fullPath: '/dj-boeken-apeldoorn'
      preLoaderRoute: typeof DjBoekenApeldoornRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-amsterdam': {
      id: '/dj-boeken-amsterdam'
      path: '/dj-boeken-amsterdam'
      fullPath: '/dj-boeken-amsterdam'
      preLoaderRoute: typeof DjBoekenAmsterdamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-amersfoort': {
      id: '/dj-boeken-amersfoort'
      path: '/dj-boeken-amersfoort'
      fullPath: '/dj-boeken-amersfoort'
      preLoaderRoute: typeof DjBoekenAmersfoortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-almere': {
      id: '/dj-boeken-almere'
      path: '/dj-boeken-almere'
      fullPath: '/dj-boeken-almere'
      preLoaderRoute: typeof DjBoekenAlmereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-alkmaar': {
      id: '/dj-boeken-alkmaar'
      path: '/dj-boeken-alkmaar'
      fullPath: '/dj-boeken-alkmaar'
      preLoaderRoute: typeof DjBoekenAlkmaarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bruiloft-dj': {
      id: '/bruiloft-dj'
      path: '/bruiloft-dj'
      fullPath: '/bruiloft-dj'
      preLoaderRoute: typeof BruiloftDjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biografie': {
      id: '/biografie'
      path: '/biografie'
      fullPath: '/biografie'
      preLoaderRoute: typeof BiografieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algemene-voorwaarden': {
      id: '/algemene-voorwaarden'
      path: '/algemene-voorwaarden'
      fullPath: '/algemene-voorwaarden'
      preLoaderRoute: typeof AlgemeneVoorwaardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlgemeneVoorwaardenRoute: AlgemeneVoorwaardenRoute,
  BiografieRoute: BiografieRoute,
  BruiloftDjRoute: BruiloftDjRoute,
  ContactRoute: ContactRoute,
  DjBoekenAlkmaarRoute: DjBoekenAlkmaarRoute,
  DjBoekenAlmereRoute: DjBoekenAlmereRoute,
  DjBoekenAmersfoortRoute: DjBoekenAmersfoortRoute,
  DjBoekenAmsterdamRoute: DjBoekenAmsterdamRoute,
  DjBoekenApeldoornRoute: DjBoekenApeldoornRoute,
  DjBoekenArnhemRoute: DjBoekenArnhemRoute,
  DjBoekenAssenRoute: DjBoekenAssenRoute,
  DjBoekenBetuweRoute: DjBoekenBetuweRoute,
  DjBoekenBredaRoute: DjBoekenBredaRoute,
  DjBoekenCulemborgRoute: DjBoekenCulemborgRoute,
  DjBoekenDelftRoute: DjBoekenDelftRoute,
  DjBoekenDenBoschRoute: DjBoekenDenBoschRoute,
  DjBoekenDenHaagRoute: DjBoekenDenHaagRoute,
  DjBoekenDeventerRoute: DjBoekenDeventerRoute,
  DjBoekenDordrechtRoute: DjBoekenDordrechtRoute,
  DjBoekenEdeRoute: DjBoekenEdeRoute,
  DjBoekenEindhovenRoute: DjBoekenEindhovenRoute,
  DjBoekenEnschedeRoute: DjBoekenEnschedeRoute,
  DjBoekenGeldermalsenRoute: DjBoekenGeldermalsenRoute,
  DjBoekenGorinchemRoute: DjBoekenGorinchemRoute,
  DjBoekenGoudaRoute: DjBoekenGoudaRoute,
  DjBoekenGroningenRoute: DjBoekenGroningenRoute,
  DjBoekenHaarlemRoute: DjBoekenHaarlemRoute,
  DjBoekenHelmondRoute: DjBoekenHelmondRoute,
  DjBoekenHilversumRoute: DjBoekenHilversumRoute,
  DjBoekenHoekscheWaardRoute: DjBoekenHoekscheWaardRoute,
  DjBoekenHoutenRoute: DjBoekenHoutenRoute,
  DjBoekenLeeuwardenRoute: DjBoekenLeeuwardenRoute,
  DjBoekenLeidenRoute: DjBoekenLeidenRoute,
  DjBoekenMaastrichtRoute: DjBoekenMaastrichtRoute,
  DjBoekenMiddelburgRoute: DjBoekenMiddelburgRoute,
  DjBoekenNieuwegeinRoute: DjBoekenNieuwegeinRoute,
  DjBoekenNijmegenRoute: DjBoekenNijmegenRoute,
  DjBoekenOphemertRoute: DjBoekenOphemertRoute,
  DjBoekenOssRoute: DjBoekenOssRoute,
  DjBoekenRoermondRoute: DjBoekenRoermondRoute,
  DjBoekenRotterdamRoute: DjBoekenRotterdamRoute,
  DjBoekenSchiedamRoute: DjBoekenSchiedamRoute,
  DjBoekenSpijkenisseRoute: DjBoekenSpijkenisseRoute,
  DjBoekenTielRoute: DjBoekenTielRoute,
  DjBoekenTilburgRoute: DjBoekenTilburgRoute,
  DjBoekenTuilRoute: DjBoekenTuilRoute,
  DjBoekenUtrechtRoute: DjBoekenUtrechtRoute,
  DjBoekenVarikRoute: DjBoekenVarikRoute,
  DjBoekenVeenendaalRoute: DjBoekenVeenendaalRoute,
  DjBoekenVenloRoute: DjBoekenVenloRoute,
  DjBoekenWageningenRoute: DjBoekenWageningenRoute,
  DjBoekenZaltbommelRoute: DjBoekenZaltbommelRoute,
  DjBoekenZeistRoute: DjBoekenZeistRoute,
  DjBoekenZoetermeerRoute: DjBoekenZoetermeerRoute,
  DjBoekenZwolleRoute: DjBoekenZwolleRoute,
  FestivalDjRoute: FestivalDjRoute,
  PrijzenRoute: PrijzenRoute,
  PrivacyRoute: PrivacyRoute,
  RegiosRoute: RegiosRoute,
  ReviewsRoute: ReviewsRoute,
  VerjaardagDjRoute: VerjaardagDjRoute,
  WerkwijzeRoute: WerkwijzeRoute,
  ZakelijkDjRoute: ZakelijkDjRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
