/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZakelijkDjRouteImport } from './routes/zakelijk-dj'
import { Route as WerkwijzeRouteImport } from './routes/werkwijze'
import { Route as VerzoekjeRouteImport } from './routes/verzoekje'
import { Route as VerjaardagDjRouteImport } from './routes/verjaardag-dj'
import { Route as TuinfeestRouteImport } from './routes/tuinfeest'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RegiosRouteImport } from './routes/regios'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrijzenRouteImport } from './routes/prijzen'
import { Route as PersoneelsfeestDjRouteImport } from './routes/personeelsfeest-dj'
import { Route as HorecaRouteImport } from './routes/horeca'
import { Route as FestivalDjRouteImport } from './routes/festival-dj'
import { Route as FeestOpLocatieRouteImport } from './routes/feest-op-locatie'
import { Route as DjEnMcRouteImport } from './routes/dj-en-mc'
import { Route as DjBoekenZwolleRouteImport } from './routes/dj-boeken-zwolle'
import { Route as DjBoekenZwijndrechtRouteImport } from './routes/dj-boeken-zwijndrecht'
import { Route as DjBoekenZuidHollandRouteImport } from './routes/dj-boeken-zuid-holland'
import { Route as DjBoekenZuidBeijerlandRouteImport } from './routes/dj-boeken-zuid-beijerland'
import { Route as DjBoekenZoetermeerRouteImport } from './routes/dj-boeken-zoetermeer'
import { Route as DjBoekenZeistRouteImport } from './routes/dj-boeken-zeist'
import { Route as DjBoekenZaltbommelRouteImport } from './routes/dj-boeken-zaltbommel'
import { Route as DjBoekenWestmaasRouteImport } from './routes/dj-boeken-westmaas'
import { Route as DjBoekenWageningenRouteImport } from './routes/dj-boeken-wageningen'
import { Route as DjBoekenVlaardingenRouteImport } from './routes/dj-boeken-vlaardingen'
import { Route as DjBoekenVenloRouteImport } from './routes/dj-boeken-venlo'
import { Route as DjBoekenVeenendaalRouteImport } from './routes/dj-boeken-veenendaal'
import { Route as DjBoekenVarikRouteImport } from './routes/dj-boeken-varik'
import { Route as DjBoekenUtrechtRouteImport } from './routes/dj-boeken-utrecht'
import { Route as DjBoekenTuilRouteImport } from './routes/dj-boeken-tuil'
import { Route as DjBoekenTilburgRouteImport } from './routes/dj-boeken-tilburg'
import { Route as DjBoekenTiengemetenRouteImport } from './routes/dj-boeken-tiengemeten'
import { Route as DjBoekenTielRouteImport } from './routes/dj-boeken-tiel'
import { Route as DjBoekenStrijensasRouteImport } from './routes/dj-boeken-strijensas'
import { Route as DjBoekenStrijenRouteImport } from './routes/dj-boeken-strijen'
import { Route as DjBoekenSpijkenisseRouteImport } from './routes/dj-boeken-spijkenisse'
import { Route as DjBoekenSliedrechtRouteImport } from './routes/dj-boeken-sliedrecht'
import { Route as DjBoekenSchiedamRouteImport } from './routes/dj-boeken-schiedam'
import { Route as DjBoekenSGravendeelRouteImport } from './routes/dj-boeken-s-gravendeel'
import { Route as DjBoekenRotterdamRouteImport } from './routes/dj-boeken-rotterdam'
import { Route as DjBoekenRoermondRouteImport } from './routes/dj-boeken-roermond'
import { Route as DjBoekenRivierenlandRouteImport } from './routes/dj-boeken-rivierenland'
import { Route as DjBoekenRidderkerkRouteImport } from './routes/dj-boeken-ridderkerk'
import { Route as DjBoekenRhoonRouteImport } from './routes/dj-boeken-rhoon'
import { Route as DjBoekenPuttershoekRouteImport } from './routes/dj-boeken-puttershoek'
import { Route as DjBoekenPoortugaalRouteImport } from './routes/dj-boeken-poortugaal'
import { Route as DjBoekenPiershilRouteImport } from './routes/dj-boeken-piershil'
import { Route as DjBoekenPapendrechtRouteImport } from './routes/dj-boeken-papendrecht'
import { Route as DjBoekenOudBeijerlandRouteImport } from './routes/dj-boeken-oud-beijerland'
import { Route as DjBoekenOssRouteImport } from './routes/dj-boeken-oss'
import { Route as DjBoekenOphemertRouteImport } from './routes/dj-boeken-ophemert'
import { Route as DjBoekenNumansdorpRouteImport } from './routes/dj-boeken-numansdorp'
import { Route as DjBoekenNijmegenRouteImport } from './routes/dj-boeken-nijmegen'
import { Route as DjBoekenNieuwegeinRouteImport } from './routes/dj-boeken-nieuwegein'
import { Route as DjBoekenNieuwBeijerlandRouteImport } from './routes/dj-boeken-nieuw-beijerland'
import { Route as DjBoekenMijnsheerenlandRouteImport } from './routes/dj-boeken-mijnsheerenland'
import { Route as DjBoekenMiddelburgRouteImport } from './routes/dj-boeken-middelburg'
import { Route as DjBoekenMaastrichtRouteImport } from './routes/dj-boeken-maastricht'
import { Route as DjBoekenMaasdamRouteImport } from './routes/dj-boeken-maasdam'
import { Route as DjBoekenLeidenRouteImport } from './routes/dj-boeken-leiden'
import { Route as DjBoekenLeeuwardenRouteImport } from './routes/dj-boeken-leeuwarden'
import { Route as DjBoekenLeerdamRouteImport } from './routes/dj-boeken-leerdam'
import { Route as DjBoekenKlaaswaalRouteImport } from './routes/dj-boeken-klaaswaal'
import { Route as DjBoekenHoutenRouteImport } from './routes/dj-boeken-houten'
import { Route as DjBoekenHoekscheWaardRouteImport } from './routes/dj-boeken-hoeksche-waard'
import { Route as DjBoekenHilversumRouteImport } from './routes/dj-boeken-hilversum'
import { Route as DjBoekenHendrikIdoAmbachtRouteImport } from './routes/dj-boeken-hendrik-ido-ambacht'
import { Route as DjBoekenHelmondRouteImport } from './routes/dj-boeken-helmond'
import { Route as DjBoekenHeinenoordRouteImport } from './routes/dj-boeken-heinenoord'
import { Route as DjBoekenHardinxveldGiessendamRouteImport } from './routes/dj-boeken-hardinxveld-giessendam'
import { Route as DjBoekenHaarlemRouteImport } from './routes/dj-boeken-haarlem'
import { Route as DjBoekenGroningenRouteImport } from './routes/dj-boeken-groningen'
import { Route as DjBoekenGoudswaardRouteImport } from './routes/dj-boeken-goudswaard'
import { Route as DjBoekenGoudaRouteImport } from './routes/dj-boeken-gouda'
import { Route as DjBoekenGorinchemRouteImport } from './routes/dj-boeken-gorinchem'
import { Route as DjBoekenGorcumRouteImport } from './routes/dj-boeken-gorcum'
import { Route as DjBoekenGeldermalsenRouteImport } from './routes/dj-boeken-geldermalsen'
import { Route as DjBoekenEnschedeRouteImport } from './routes/dj-boeken-enschede'
import { Route as DjBoekenEindhovenRouteImport } from './routes/dj-boeken-eindhoven'
import { Route as DjBoekenEdeRouteImport } from './routes/dj-boeken-ede'
import { Route as DjBoekenDordrechtRouteImport } from './routes/dj-boeken-dordrecht'
import { Route as DjBoekenDeventerRouteImport } from './routes/dj-boeken-deventer'
import { Route as DjBoekenDenHaagRouteImport } from './routes/dj-boeken-den-haag'
import { Route as DjBoekenDenBoschRouteImport } from './routes/dj-boeken-den-bosch'
import { Route as DjBoekenDelftRouteImport } from './routes/dj-boeken-delft'
import { Route as DjBoekenCulemborgRouteImport } from './routes/dj-boeken-culemborg'
import { Route as DjBoekenCillaarshoekRouteImport } from './routes/dj-boeken-cillaarshoek'
import { Route as DjBoekenCapelleAanDenIjsselRouteImport } from './routes/dj-boeken-capelle-aan-den-ijssel'
import { Route as DjBoekenBurenRouteImport } from './routes/dj-boeken-buren'
import { Route as DjBoekenBredaRouteImport } from './routes/dj-boeken-breda'
import { Route as DjBoekenBommelerwaardRouteImport } from './routes/dj-boeken-bommelerwaard'
import { Route as DjBoekenBetuweRouteImport } from './routes/dj-boeken-betuwe'
import { Route as DjBoekenBarendrechtRouteImport } from './routes/dj-boeken-barendrecht'
import { Route as DjBoekenAssenRouteImport } from './routes/dj-boeken-assen'
import { Route as DjBoekenArnhemRouteImport } from './routes/dj-boeken-arnhem'
import { Route as DjBoekenApeldoornRouteImport } from './routes/dj-boeken-apeldoorn'
import { Route as DjBoekenAmsterdamRouteImport } from './routes/dj-boeken-amsterdam'
import { Route as DjBoekenAmstelveenRouteImport } from './routes/dj-boeken-amstelveen'
import { Route as DjBoekenAmersfoortRouteImport } from './routes/dj-boeken-amersfoort'
import { Route as DjBoekenAlphenAanDenRijnRouteImport } from './routes/dj-boeken-alphen-aan-den-rijn'
import { Route as DjBoekenAlmereRouteImport } from './routes/dj-boeken-almere'
import { Route as DjBoekenAlkmaarRouteImport } from './routes/dj-boeken-alkmaar'
import { Route as DjBoekenAlbrandswaardRouteImport } from './routes/dj-boeken-albrandswaard'
import { Route as DjBoekenAlblasserdamRouteImport } from './routes/dj-boeken-alblasserdam'
import { Route as DjRouteImport } from './routes/dj'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BruiloftDjTielRouteImport } from './routes/bruiloft-dj-tiel'
import { Route as BruiloftDjRotterdamRouteImport } from './routes/bruiloft-dj-rotterdam'
import { Route as BruiloftDjHoekscheWaardRouteImport } from './routes/bruiloft-dj-hoeksche-waard'
import { Route as BruiloftDjDordrechtRouteImport } from './routes/bruiloft-dj-dordrecht'
import { Route as BruiloftDjBetuweRouteImport } from './routes/bruiloft-dj-betuwe'
import { Route as BruiloftDjRouteImport } from './routes/bruiloft-dj'
import { Route as BiografieRouteImport } from './routes/biografie'
import { Route as ArtiestenRouteImport } from './routes/artiesten'
import { Route as AlgemeneVoorwaardenRouteImport } from './routes/algemene-voorwaarden'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const ZakelijkDjRoute = ZakelijkDjRouteImport.update({
  id: '/zakelijk-dj',
  path: '/zakelijk-dj',
  getParentRoute: () => rootRouteImport,
} as any)
const WerkwijzeRoute = WerkwijzeRouteImport.update({
  id: '/werkwijze',
  path: '/werkwijze',
  getParentRoute: () => rootRouteImport,
} as any)
const VerzoekjeRoute = VerzoekjeRouteImport.update({
  id: '/verzoekje',
  path: '/verzoekje',
  getParentRoute: () => rootRouteImport,
} as any)
const VerjaardagDjRoute = VerjaardagDjRouteImport.update({
  id: '/verjaardag-dj',
  path: '/verjaardag-dj',
  getParentRoute: () => rootRouteImport,
} as any)
const TuinfeestRoute = TuinfeestRouteImport.update({
  id: '/tuinfeest',
  path: '/tuinfeest',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RegiosRoute = RegiosRouteImport.update({
  id: '/regios',
  path: '/regios',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrijzenRoute = PrijzenRouteImport.update({
  id: '/prijzen',
  path: '/prijzen',
  getParentRoute: () => rootRouteImport,
} as any)
const PersoneelsfeestDjRoute = PersoneelsfeestDjRouteImport.update({
  id: '/personeelsfeest-dj',
  path: '/personeelsfeest-dj',
  getParentRoute: () => rootRouteImport,
} as any)
const HorecaRoute = HorecaRouteImport.update({
  id: '/horeca',
  path: '/horeca',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalDjRoute = FestivalDjRouteImport.update({
  id: '/festival-dj',
  path: '/festival-dj',
  getParentRoute: () => rootRouteImport,
} as any)
const FeestOpLocatieRoute = FeestOpLocatieRouteImport.update({
  id: '/feest-op-locatie',
  path: '/feest-op-locatie',
  getParentRoute: () => rootRouteImport,
} as any)
const DjEnMcRoute = DjEnMcRouteImport.update({
  id: '/dj-en-mc',
  path: '/dj-en-mc',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenZwolleRoute = DjBoekenZwolleRouteImport.update({
  id: '/dj-boeken-zwolle',
  path: '/dj-boeken-zwolle',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenZwijndrechtRoute = DjBoekenZwijndrechtRouteImport.update({
  id: '/dj-boeken-zwijndrecht',
  path: '/dj-boeken-zwijndrecht',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenZuidHollandRoute = DjBoekenZuidHollandRouteImport.update({
  id: '/dj-boeken-zuid-holland',
  path: '/dj-boeken-zuid-holland',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenZuidBeijerlandRoute = DjBoekenZuidBeijerlandRouteImport.update({
  id: '/dj-boeken-zuid-beijerland',
  path: '/dj-boeken-zuid-beijerland',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenZoetermeerRoute = DjBoekenZoetermeerRouteImport.update({
  id: '/dj-boeken-zoetermeer',
  path: '/dj-boeken-zoetermeer',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenZeistRoute = DjBoekenZeistRouteImport.update({
  id: '/dj-boeken-zeist',
  path: '/dj-boeken-zeist',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenZaltbommelRoute = DjBoekenZaltbommelRouteImport.update({
  id: '/dj-boeken-zaltbommel',
  path: '/dj-boeken-zaltbommel',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenWestmaasRoute = DjBoekenWestmaasRouteImport.update({
  id: '/dj-boeken-westmaas',
  path: '/dj-boeken-westmaas',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenWageningenRoute = DjBoekenWageningenRouteImport.update({
  id: '/dj-boeken-wageningen',
  path: '/dj-boeken-wageningen',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenVlaardingenRoute = DjBoekenVlaardingenRouteImport.update({
  id: '/dj-boeken-vlaardingen',
  path: '/dj-boeken-vlaardingen',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenVenloRoute = DjBoekenVenloRouteImport.update({
  id: '/dj-boeken-venlo',
  path: '/dj-boeken-venlo',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenVeenendaalRoute = DjBoekenVeenendaalRouteImport.update({
  id: '/dj-boeken-veenendaal',
  path: '/dj-boeken-veenendaal',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenVarikRoute = DjBoekenVarikRouteImport.update({
  id: '/dj-boeken-varik',
  path: '/dj-boeken-varik',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenUtrechtRoute = DjBoekenUtrechtRouteImport.update({
  id: '/dj-boeken-utrecht',
  path: '/dj-boeken-utrecht',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenTuilRoute = DjBoekenTuilRouteImport.update({
  id: '/dj-boeken-tuil',
  path: '/dj-boeken-tuil',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenTilburgRoute = DjBoekenTilburgRouteImport.update({
  id: '/dj-boeken-tilburg',
  path: '/dj-boeken-tilburg',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenTiengemetenRoute = DjBoekenTiengemetenRouteImport.update({
  id: '/dj-boeken-tiengemeten',
  path: '/dj-boeken-tiengemeten',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenTielRoute = DjBoekenTielRouteImport.update({
  id: '/dj-boeken-tiel',
  path: '/dj-boeken-tiel',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenStrijensasRoute = DjBoekenStrijensasRouteImport.update({
  id: '/dj-boeken-strijensas',
  path: '/dj-boeken-strijensas',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenStrijenRoute = DjBoekenStrijenRouteImport.update({
  id: '/dj-boeken-strijen',
  path: '/dj-boeken-strijen',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenSpijkenisseRoute = DjBoekenSpijkenisseRouteImport.update({
  id: '/dj-boeken-spijkenisse',
  path: '/dj-boeken-spijkenisse',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenSliedrechtRoute = DjBoekenSliedrechtRouteImport.update({
  id: '/dj-boeken-sliedrecht',
  path: '/dj-boeken-sliedrecht',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenSchiedamRoute = DjBoekenSchiedamRouteImport.update({
  id: '/dj-boeken-schiedam',
  path: '/dj-boeken-schiedam',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenSGravendeelRoute = DjBoekenSGravendeelRouteImport.update({
  id: '/dj-boeken-s-gravendeel',
  path: '/dj-boeken-s-gravendeel',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenRotterdamRoute = DjBoekenRotterdamRouteImport.update({
  id: '/dj-boeken-rotterdam',
  path: '/dj-boeken-rotterdam',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenRoermondRoute = DjBoekenRoermondRouteImport.update({
  id: '/dj-boeken-roermond',
  path: '/dj-boeken-roermond',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenRivierenlandRoute = DjBoekenRivierenlandRouteImport.update({
  id: '/dj-boeken-rivierenland',
  path: '/dj-boeken-rivierenland',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenRidderkerkRoute = DjBoekenRidderkerkRouteImport.update({
  id: '/dj-boeken-ridderkerk',
  path: '/dj-boeken-ridderkerk',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenRhoonRoute = DjBoekenRhoonRouteImport.update({
  id: '/dj-boeken-rhoon',
  path: '/dj-boeken-rhoon',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenPuttershoekRoute = DjBoekenPuttershoekRouteImport.update({
  id: '/dj-boeken-puttershoek',
  path: '/dj-boeken-puttershoek',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenPoortugaalRoute = DjBoekenPoortugaalRouteImport.update({
  id: '/dj-boeken-poortugaal',
  path: '/dj-boeken-poortugaal',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenPiershilRoute = DjBoekenPiershilRouteImport.update({
  id: '/dj-boeken-piershil',
  path: '/dj-boeken-piershil',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenPapendrechtRoute = DjBoekenPapendrechtRouteImport.update({
  id: '/dj-boeken-papendrecht',
  path: '/dj-boeken-papendrecht',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenOudBeijerlandRoute = DjBoekenOudBeijerlandRouteImport.update({
  id: '/dj-boeken-oud-beijerland',
  path: '/dj-boeken-oud-beijerland',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenOssRoute = DjBoekenOssRouteImport.update({
  id: '/dj-boeken-oss',
  path: '/dj-boeken-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenOphemertRoute = DjBoekenOphemertRouteImport.update({
  id: '/dj-boeken-ophemert',
  path: '/dj-boeken-ophemert',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenNumansdorpRoute = DjBoekenNumansdorpRouteImport.update({
  id: '/dj-boeken-numansdorp',
  path: '/dj-boeken-numansdorp',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenNijmegenRoute = DjBoekenNijmegenRouteImport.update({
  id: '/dj-boeken-nijmegen',
  path: '/dj-boeken-nijmegen',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenNieuwegeinRoute = DjBoekenNieuwegeinRouteImport.update({
  id: '/dj-boeken-nieuwegein',
  path: '/dj-boeken-nieuwegein',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenNieuwBeijerlandRoute = DjBoekenNieuwBeijerlandRouteImport.update({
  id: '/dj-boeken-nieuw-beijerland',
  path: '/dj-boeken-nieuw-beijerland',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenMijnsheerenlandRoute = DjBoekenMijnsheerenlandRouteImport.update({
  id: '/dj-boeken-mijnsheerenland',
  path: '/dj-boeken-mijnsheerenland',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenMiddelburgRoute = DjBoekenMiddelburgRouteImport.update({
  id: '/dj-boeken-middelburg',
  path: '/dj-boeken-middelburg',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenMaastrichtRoute = DjBoekenMaastrichtRouteImport.update({
  id: '/dj-boeken-maastricht',
  path: '/dj-boeken-maastricht',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenMaasdamRoute = DjBoekenMaasdamRouteImport.update({
  id: '/dj-boeken-maasdam',
  path: '/dj-boeken-maasdam',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenLeidenRoute = DjBoekenLeidenRouteImport.update({
  id: '/dj-boeken-leiden',
  path: '/dj-boeken-leiden',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenLeeuwardenRoute = DjBoekenLeeuwardenRouteImport.update({
  id: '/dj-boeken-leeuwarden',
  path: '/dj-boeken-leeuwarden',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenLeerdamRoute = DjBoekenLeerdamRouteImport.update({
  id: '/dj-boeken-leerdam',
  path: '/dj-boeken-leerdam',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenKlaaswaalRoute = DjBoekenKlaaswaalRouteImport.update({
  id: '/dj-boeken-klaaswaal',
  path: '/dj-boeken-klaaswaal',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenHoutenRoute = DjBoekenHoutenRouteImport.update({
  id: '/dj-boeken-houten',
  path: '/dj-boeken-houten',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenHoekscheWaardRoute = DjBoekenHoekscheWaardRouteImport.update({
  id: '/dj-boeken-hoeksche-waard',
  path: '/dj-boeken-hoeksche-waard',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenHilversumRoute = DjBoekenHilversumRouteImport.update({
  id: '/dj-boeken-hilversum',
  path: '/dj-boeken-hilversum',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenHendrikIdoAmbachtRoute =
  DjBoekenHendrikIdoAmbachtRouteImport.update({
    id: '/dj-boeken-hendrik-ido-ambacht',
    path: '/dj-boeken-hendrik-ido-ambacht',
    getParentRoute: () => rootRouteImport,
  } as any)
const DjBoekenHelmondRoute = DjBoekenHelmondRouteImport.update({
  id: '/dj-boeken-helmond',
  path: '/dj-boeken-helmond',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenHeinenoordRoute = DjBoekenHeinenoordRouteImport.update({
  id: '/dj-boeken-heinenoord',
  path: '/dj-boeken-heinenoord',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenHardinxveldGiessendamRoute =
  DjBoekenHardinxveldGiessendamRouteImport.update({
    id: '/dj-boeken-hardinxveld-giessendam',
    path: '/dj-boeken-hardinxveld-giessendam',
    getParentRoute: () => rootRouteImport,
  } as any)
const DjBoekenHaarlemRoute = DjBoekenHaarlemRouteImport.update({
  id: '/dj-boeken-haarlem',
  path: '/dj-boeken-haarlem',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenGroningenRoute = DjBoekenGroningenRouteImport.update({
  id: '/dj-boeken-groningen',
  path: '/dj-boeken-groningen',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenGoudswaardRoute = DjBoekenGoudswaardRouteImport.update({
  id: '/dj-boeken-goudswaard',
  path: '/dj-boeken-goudswaard',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenGoudaRoute = DjBoekenGoudaRouteImport.update({
  id: '/dj-boeken-gouda',
  path: '/dj-boeken-gouda',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenGorinchemRoute = DjBoekenGorinchemRouteImport.update({
  id: '/dj-boeken-gorinchem',
  path: '/dj-boeken-gorinchem',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenGorcumRoute = DjBoekenGorcumRouteImport.update({
  id: '/dj-boeken-gorcum',
  path: '/dj-boeken-gorcum',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenGeldermalsenRoute = DjBoekenGeldermalsenRouteImport.update({
  id: '/dj-boeken-geldermalsen',
  path: '/dj-boeken-geldermalsen',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenEnschedeRoute = DjBoekenEnschedeRouteImport.update({
  id: '/dj-boeken-enschede',
  path: '/dj-boeken-enschede',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenEindhovenRoute = DjBoekenEindhovenRouteImport.update({
  id: '/dj-boeken-eindhoven',
  path: '/dj-boeken-eindhoven',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenEdeRoute = DjBoekenEdeRouteImport.update({
  id: '/dj-boeken-ede',
  path: '/dj-boeken-ede',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenDordrechtRoute = DjBoekenDordrechtRouteImport.update({
  id: '/dj-boeken-dordrecht',
  path: '/dj-boeken-dordrecht',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenDeventerRoute = DjBoekenDeventerRouteImport.update({
  id: '/dj-boeken-deventer',
  path: '/dj-boeken-deventer',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenDenHaagRoute = DjBoekenDenHaagRouteImport.update({
  id: '/dj-boeken-den-haag',
  path: '/dj-boeken-den-haag',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenDenBoschRoute = DjBoekenDenBoschRouteImport.update({
  id: '/dj-boeken-den-bosch',
  path: '/dj-boeken-den-bosch',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenDelftRoute = DjBoekenDelftRouteImport.update({
  id: '/dj-boeken-delft',
  path: '/dj-boeken-delft',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenCulemborgRoute = DjBoekenCulemborgRouteImport.update({
  id: '/dj-boeken-culemborg',
  path: '/dj-boeken-culemborg',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenCillaarshoekRoute = DjBoekenCillaarshoekRouteImport.update({
  id: '/dj-boeken-cillaarshoek',
  path: '/dj-boeken-cillaarshoek',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenCapelleAanDenIjsselRoute =
  DjBoekenCapelleAanDenIjsselRouteImport.update({
    id: '/dj-boeken-capelle-aan-den-ijssel',
    path: '/dj-boeken-capelle-aan-den-ijssel',
    getParentRoute: () => rootRouteImport,
  } as any)
const DjBoekenBurenRoute = DjBoekenBurenRouteImport.update({
  id: '/dj-boeken-buren',
  path: '/dj-boeken-buren',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenBredaRoute = DjBoekenBredaRouteImport.update({
  id: '/dj-boeken-breda',
  path: '/dj-boeken-breda',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenBommelerwaardRoute = DjBoekenBommelerwaardRouteImport.update({
  id: '/dj-boeken-bommelerwaard',
  path: '/dj-boeken-bommelerwaard',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenBetuweRoute = DjBoekenBetuweRouteImport.update({
  id: '/dj-boeken-betuwe',
  path: '/dj-boeken-betuwe',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenBarendrechtRoute = DjBoekenBarendrechtRouteImport.update({
  id: '/dj-boeken-barendrecht',
  path: '/dj-boeken-barendrecht',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenAssenRoute = DjBoekenAssenRouteImport.update({
  id: '/dj-boeken-assen',
  path: '/dj-boeken-assen',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenArnhemRoute = DjBoekenArnhemRouteImport.update({
  id: '/dj-boeken-arnhem',
  path: '/dj-boeken-arnhem',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenApeldoornRoute = DjBoekenApeldoornRouteImport.update({
  id: '/dj-boeken-apeldoorn',
  path: '/dj-boeken-apeldoorn',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenAmsterdamRoute = DjBoekenAmsterdamRouteImport.update({
  id: '/dj-boeken-amsterdam',
  path: '/dj-boeken-amsterdam',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenAmstelveenRoute = DjBoekenAmstelveenRouteImport.update({
  id: '/dj-boeken-amstelveen',
  path: '/dj-boeken-amstelveen',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenAmersfoortRoute = DjBoekenAmersfoortRouteImport.update({
  id: '/dj-boeken-amersfoort',
  path: '/dj-boeken-amersfoort',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenAlphenAanDenRijnRoute =
  DjBoekenAlphenAanDenRijnRouteImport.update({
    id: '/dj-boeken-alphen-aan-den-rijn',
    path: '/dj-boeken-alphen-aan-den-rijn',
    getParentRoute: () => rootRouteImport,
  } as any)
const DjBoekenAlmereRoute = DjBoekenAlmereRouteImport.update({
  id: '/dj-boeken-almere',
  path: '/dj-boeken-almere',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenAlkmaarRoute = DjBoekenAlkmaarRouteImport.update({
  id: '/dj-boeken-alkmaar',
  path: '/dj-boeken-alkmaar',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenAlbrandswaardRoute = DjBoekenAlbrandswaardRouteImport.update({
  id: '/dj-boeken-albrandswaard',
  path: '/dj-boeken-albrandswaard',
  getParentRoute: () => rootRouteImport,
} as any)
const DjBoekenAlblasserdamRoute = DjBoekenAlblasserdamRouteImport.update({
  id: '/dj-boeken-alblasserdam',
  path: '/dj-boeken-alblasserdam',
  getParentRoute: () => rootRouteImport,
} as any)
const DjRoute = DjRouteImport.update({
  id: '/dj',
  path: '/dj',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BruiloftDjTielRoute = BruiloftDjTielRouteImport.update({
  id: '/bruiloft-dj-tiel',
  path: '/bruiloft-dj-tiel',
  getParentRoute: () => rootRouteImport,
} as any)
const BruiloftDjRotterdamRoute = BruiloftDjRotterdamRouteImport.update({
  id: '/bruiloft-dj-rotterdam',
  path: '/bruiloft-dj-rotterdam',
  getParentRoute: () => rootRouteImport,
} as any)
const BruiloftDjHoekscheWaardRoute = BruiloftDjHoekscheWaardRouteImport.update({
  id: '/bruiloft-dj-hoeksche-waard',
  path: '/bruiloft-dj-hoeksche-waard',
  getParentRoute: () => rootRouteImport,
} as any)
const BruiloftDjDordrechtRoute = BruiloftDjDordrechtRouteImport.update({
  id: '/bruiloft-dj-dordrecht',
  path: '/bruiloft-dj-dordrecht',
  getParentRoute: () => rootRouteImport,
} as any)
const BruiloftDjBetuweRoute = BruiloftDjBetuweRouteImport.update({
  id: '/bruiloft-dj-betuwe',
  path: '/bruiloft-dj-betuwe',
  getParentRoute: () => rootRouteImport,
} as any)
const BruiloftDjRoute = BruiloftDjRouteImport.update({
  id: '/bruiloft-dj',
  path: '/bruiloft-dj',
  getParentRoute: () => rootRouteImport,
} as any)
const BiografieRoute = BiografieRouteImport.update({
  id: '/biografie',
  path: '/biografie',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtiestenRoute = ArtiestenRouteImport.update({
  id: '/artiesten',
  path: '/artiesten',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgemeneVoorwaardenRoute = AlgemeneVoorwaardenRouteImport.update({
  id: '/algemene-voorwaarden',
  path: '/algemene-voorwaarden',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/artiesten': typeof ArtiestenRoute
  '/biografie': typeof BiografieRoute
  '/bruiloft-dj': typeof BruiloftDjRoute
  '/bruiloft-dj-betuwe': typeof BruiloftDjBetuweRoute
  '/bruiloft-dj-dordrecht': typeof BruiloftDjDordrechtRoute
  '/bruiloft-dj-hoeksche-waard': typeof BruiloftDjHoekscheWaardRoute
  '/bruiloft-dj-rotterdam': typeof BruiloftDjRotterdamRoute
  '/bruiloft-dj-tiel': typeof BruiloftDjTielRoute
  '/contact': typeof ContactRoute
  '/dj': typeof DjRoute
  '/dj-boeken-alblasserdam': typeof DjBoekenAlblasserdamRoute
  '/dj-boeken-albrandswaard': typeof DjBoekenAlbrandswaardRoute
  '/dj-boeken-alkmaar': typeof DjBoekenAlkmaarRoute
  '/dj-boeken-almere': typeof DjBoekenAlmereRoute
  '/dj-boeken-alphen-aan-den-rijn': typeof DjBoekenAlphenAanDenRijnRoute
  '/dj-boeken-amersfoort': typeof DjBoekenAmersfoortRoute
  '/dj-boeken-amstelveen': typeof DjBoekenAmstelveenRoute
  '/dj-boeken-amsterdam': typeof DjBoekenAmsterdamRoute
  '/dj-boeken-apeldoorn': typeof DjBoekenApeldoornRoute
  '/dj-boeken-arnhem': typeof DjBoekenArnhemRoute
  '/dj-boeken-assen': typeof DjBoekenAssenRoute
  '/dj-boeken-barendrecht': typeof DjBoekenBarendrechtRoute
  '/dj-boeken-betuwe': typeof DjBoekenBetuweRoute
  '/dj-boeken-bommelerwaard': typeof DjBoekenBommelerwaardRoute
  '/dj-boeken-breda': typeof DjBoekenBredaRoute
  '/dj-boeken-buren': typeof DjBoekenBurenRoute
  '/dj-boeken-capelle-aan-den-ijssel': typeof DjBoekenCapelleAanDenIjsselRoute
  '/dj-boeken-cillaarshoek': typeof DjBoekenCillaarshoekRoute
  '/dj-boeken-culemborg': typeof DjBoekenCulemborgRoute
  '/dj-boeken-delft': typeof DjBoekenDelftRoute
  '/dj-boeken-den-bosch': typeof DjBoekenDenBoschRoute
  '/dj-boeken-den-haag': typeof DjBoekenDenHaagRoute
  '/dj-boeken-deventer': typeof DjBoekenDeventerRoute
  '/dj-boeken-dordrecht': typeof DjBoekenDordrechtRoute
  '/dj-boeken-ede': typeof DjBoekenEdeRoute
  '/dj-boeken-eindhoven': typeof DjBoekenEindhovenRoute
  '/dj-boeken-enschede': typeof DjBoekenEnschedeRoute
  '/dj-boeken-geldermalsen': typeof DjBoekenGeldermalsenRoute
  '/dj-boeken-gorcum': typeof DjBoekenGorcumRoute
  '/dj-boeken-gorinchem': typeof DjBoekenGorinchemRoute
  '/dj-boeken-gouda': typeof DjBoekenGoudaRoute
  '/dj-boeken-goudswaard': typeof DjBoekenGoudswaardRoute
  '/dj-boeken-groningen': typeof DjBoekenGroningenRoute
  '/dj-boeken-haarlem': typeof DjBoekenHaarlemRoute
  '/dj-boeken-hardinxveld-giessendam': typeof DjBoekenHardinxveldGiessendamRoute
  '/dj-boeken-heinenoord': typeof DjBoekenHeinenoordRoute
  '/dj-boeken-helmond': typeof DjBoekenHelmondRoute
  '/dj-boeken-hendrik-ido-ambacht': typeof DjBoekenHendrikIdoAmbachtRoute
  '/dj-boeken-hilversum': typeof DjBoekenHilversumRoute
  '/dj-boeken-hoeksche-waard': typeof DjBoekenHoekscheWaardRoute
  '/dj-boeken-houten': typeof DjBoekenHoutenRoute
  '/dj-boeken-klaaswaal': typeof DjBoekenKlaaswaalRoute
  '/dj-boeken-leerdam': typeof DjBoekenLeerdamRoute
  '/dj-boeken-leeuwarden': typeof DjBoekenLeeuwardenRoute
  '/dj-boeken-leiden': typeof DjBoekenLeidenRoute
  '/dj-boeken-maasdam': typeof DjBoekenMaasdamRoute
  '/dj-boeken-maastricht': typeof DjBoekenMaastrichtRoute
  '/dj-boeken-middelburg': typeof DjBoekenMiddelburgRoute
  '/dj-boeken-mijnsheerenland': typeof DjBoekenMijnsheerenlandRoute
  '/dj-boeken-nieuw-beijerland': typeof DjBoekenNieuwBeijerlandRoute
  '/dj-boeken-nieuwegein': typeof DjBoekenNieuwegeinRoute
  '/dj-boeken-nijmegen': typeof DjBoekenNijmegenRoute
  '/dj-boeken-numansdorp': typeof DjBoekenNumansdorpRoute
  '/dj-boeken-ophemert': typeof DjBoekenOphemertRoute
  '/dj-boeken-oss': typeof DjBoekenOssRoute
  '/dj-boeken-oud-beijerland': typeof DjBoekenOudBeijerlandRoute
  '/dj-boeken-papendrecht': typeof DjBoekenPapendrechtRoute
  '/dj-boeken-piershil': typeof DjBoekenPiershilRoute
  '/dj-boeken-poortugaal': typeof DjBoekenPoortugaalRoute
  '/dj-boeken-puttershoek': typeof DjBoekenPuttershoekRoute
  '/dj-boeken-rhoon': typeof DjBoekenRhoonRoute
  '/dj-boeken-ridderkerk': typeof DjBoekenRidderkerkRoute
  '/dj-boeken-rivierenland': typeof DjBoekenRivierenlandRoute
  '/dj-boeken-roermond': typeof DjBoekenRoermondRoute
  '/dj-boeken-rotterdam': typeof DjBoekenRotterdamRoute
  '/dj-boeken-s-gravendeel': typeof DjBoekenSGravendeelRoute
  '/dj-boeken-schiedam': typeof DjBoekenSchiedamRoute
  '/dj-boeken-sliedrecht': typeof DjBoekenSliedrechtRoute
  '/dj-boeken-spijkenisse': typeof DjBoekenSpijkenisseRoute
  '/dj-boeken-strijen': typeof DjBoekenStrijenRoute
  '/dj-boeken-strijensas': typeof DjBoekenStrijensasRoute
  '/dj-boeken-tiel': typeof DjBoekenTielRoute
  '/dj-boeken-tiengemeten': typeof DjBoekenTiengemetenRoute
  '/dj-boeken-tilburg': typeof DjBoekenTilburgRoute
  '/dj-boeken-tuil': typeof DjBoekenTuilRoute
  '/dj-boeken-utrecht': typeof DjBoekenUtrechtRoute
  '/dj-boeken-varik': typeof DjBoekenVarikRoute
  '/dj-boeken-veenendaal': typeof DjBoekenVeenendaalRoute
  '/dj-boeken-venlo': typeof DjBoekenVenloRoute
  '/dj-boeken-vlaardingen': typeof DjBoekenVlaardingenRoute
  '/dj-boeken-wageningen': typeof DjBoekenWageningenRoute
  '/dj-boeken-westmaas': typeof DjBoekenWestmaasRoute
  '/dj-boeken-zaltbommel': typeof DjBoekenZaltbommelRoute
  '/dj-boeken-zeist': typeof DjBoekenZeistRoute
  '/dj-boeken-zoetermeer': typeof DjBoekenZoetermeerRoute
  '/dj-boeken-zuid-beijerland': typeof DjBoekenZuidBeijerlandRoute
  '/dj-boeken-zuid-holland': typeof DjBoekenZuidHollandRoute
  '/dj-boeken-zwijndrecht': typeof DjBoekenZwijndrechtRoute
  '/dj-boeken-zwolle': typeof DjBoekenZwolleRoute
  '/dj-en-mc': typeof DjEnMcRoute
  '/feest-op-locatie': typeof FeestOpLocatieRoute
  '/festival-dj': typeof FestivalDjRoute
  '/horeca': typeof HorecaRoute
  '/personeelsfeest-dj': typeof PersoneelsfeestDjRoute
  '/prijzen': typeof PrijzenRoute
  '/privacy': typeof PrivacyRoute
  '/regios': typeof RegiosRoute
  '/reviews': typeof ReviewsRoute
  '/tuinfeest': typeof TuinfeestRoute
  '/verjaardag-dj': typeof VerjaardagDjRoute
  '/verzoekje': typeof VerzoekjeRoute
  '/werkwijze': typeof WerkwijzeRoute
  '/zakelijk-dj': typeof ZakelijkDjRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/artiesten': typeof ArtiestenRoute
  '/biografie': typeof BiografieRoute
  '/bruiloft-dj': typeof BruiloftDjRoute
  '/bruiloft-dj-betuwe': typeof BruiloftDjBetuweRoute
  '/bruiloft-dj-dordrecht': typeof BruiloftDjDordrechtRoute
  '/bruiloft-dj-hoeksche-waard': typeof BruiloftDjHoekscheWaardRoute
  '/bruiloft-dj-rotterdam': typeof BruiloftDjRotterdamRoute
  '/bruiloft-dj-tiel': typeof BruiloftDjTielRoute
  '/contact': typeof ContactRoute
  '/dj': typeof DjRoute
  '/dj-boeken-alblasserdam': typeof DjBoekenAlblasserdamRoute
  '/dj-boeken-albrandswaard': typeof DjBoekenAlbrandswaardRoute
  '/dj-boeken-alkmaar': typeof DjBoekenAlkmaarRoute
  '/dj-boeken-almere': typeof DjBoekenAlmereRoute
  '/dj-boeken-alphen-aan-den-rijn': typeof DjBoekenAlphenAanDenRijnRoute
  '/dj-boeken-amersfoort': typeof DjBoekenAmersfoortRoute
  '/dj-boeken-amstelveen': typeof DjBoekenAmstelveenRoute
  '/dj-boeken-amsterdam': typeof DjBoekenAmsterdamRoute
  '/dj-boeken-apeldoorn': typeof DjBoekenApeldoornRoute
  '/dj-boeken-arnhem': typeof DjBoekenArnhemRoute
  '/dj-boeken-assen': typeof DjBoekenAssenRoute
  '/dj-boeken-barendrecht': typeof DjBoekenBarendrechtRoute
  '/dj-boeken-betuwe': typeof DjBoekenBetuweRoute
  '/dj-boeken-bommelerwaard': typeof DjBoekenBommelerwaardRoute
  '/dj-boeken-breda': typeof DjBoekenBredaRoute
  '/dj-boeken-buren': typeof DjBoekenBurenRoute
  '/dj-boeken-capelle-aan-den-ijssel': typeof DjBoekenCapelleAanDenIjsselRoute
  '/dj-boeken-cillaarshoek': typeof DjBoekenCillaarshoekRoute
  '/dj-boeken-culemborg': typeof DjBoekenCulemborgRoute
  '/dj-boeken-delft': typeof DjBoekenDelftRoute
  '/dj-boeken-den-bosch': typeof DjBoekenDenBoschRoute
  '/dj-boeken-den-haag': typeof DjBoekenDenHaagRoute
  '/dj-boeken-deventer': typeof DjBoekenDeventerRoute
  '/dj-boeken-dordrecht': typeof DjBoekenDordrechtRoute
  '/dj-boeken-ede': typeof DjBoekenEdeRoute
  '/dj-boeken-eindhoven': typeof DjBoekenEindhovenRoute
  '/dj-boeken-enschede': typeof DjBoekenEnschedeRoute
  '/dj-boeken-geldermalsen': typeof DjBoekenGeldermalsenRoute
  '/dj-boeken-gorcum': typeof DjBoekenGorcumRoute
  '/dj-boeken-gorinchem': typeof DjBoekenGorinchemRoute
  '/dj-boeken-gouda': typeof DjBoekenGoudaRoute
  '/dj-boeken-goudswaard': typeof DjBoekenGoudswaardRoute
  '/dj-boeken-groningen': typeof DjBoekenGroningenRoute
  '/dj-boeken-haarlem': typeof DjBoekenHaarlemRoute
  '/dj-boeken-hardinxveld-giessendam': typeof DjBoekenHardinxveldGiessendamRoute
  '/dj-boeken-heinenoord': typeof DjBoekenHeinenoordRoute
  '/dj-boeken-helmond': typeof DjBoekenHelmondRoute
  '/dj-boeken-hendrik-ido-ambacht': typeof DjBoekenHendrikIdoAmbachtRoute
  '/dj-boeken-hilversum': typeof DjBoekenHilversumRoute
  '/dj-boeken-hoeksche-waard': typeof DjBoekenHoekscheWaardRoute
  '/dj-boeken-houten': typeof DjBoekenHoutenRoute
  '/dj-boeken-klaaswaal': typeof DjBoekenKlaaswaalRoute
  '/dj-boeken-leerdam': typeof DjBoekenLeerdamRoute
  '/dj-boeken-leeuwarden': typeof DjBoekenLeeuwardenRoute
  '/dj-boeken-leiden': typeof DjBoekenLeidenRoute
  '/dj-boeken-maasdam': typeof DjBoekenMaasdamRoute
  '/dj-boeken-maastricht': typeof DjBoekenMaastrichtRoute
  '/dj-boeken-middelburg': typeof DjBoekenMiddelburgRoute
  '/dj-boeken-mijnsheerenland': typeof DjBoekenMijnsheerenlandRoute
  '/dj-boeken-nieuw-beijerland': typeof DjBoekenNieuwBeijerlandRoute
  '/dj-boeken-nieuwegein': typeof DjBoekenNieuwegeinRoute
  '/dj-boeken-nijmegen': typeof DjBoekenNijmegenRoute
  '/dj-boeken-numansdorp': typeof DjBoekenNumansdorpRoute
  '/dj-boeken-ophemert': typeof DjBoekenOphemertRoute
  '/dj-boeken-oss': typeof DjBoekenOssRoute
  '/dj-boeken-oud-beijerland': typeof DjBoekenOudBeijerlandRoute
  '/dj-boeken-papendrecht': typeof DjBoekenPapendrechtRoute
  '/dj-boeken-piershil': typeof DjBoekenPiershilRoute
  '/dj-boeken-poortugaal': typeof DjBoekenPoortugaalRoute
  '/dj-boeken-puttershoek': typeof DjBoekenPuttershoekRoute
  '/dj-boeken-rhoon': typeof DjBoekenRhoonRoute
  '/dj-boeken-ridderkerk': typeof DjBoekenRidderkerkRoute
  '/dj-boeken-rivierenland': typeof DjBoekenRivierenlandRoute
  '/dj-boeken-roermond': typeof DjBoekenRoermondRoute
  '/dj-boeken-rotterdam': typeof DjBoekenRotterdamRoute
  '/dj-boeken-s-gravendeel': typeof DjBoekenSGravendeelRoute
  '/dj-boeken-schiedam': typeof DjBoekenSchiedamRoute
  '/dj-boeken-sliedrecht': typeof DjBoekenSliedrechtRoute
  '/dj-boeken-spijkenisse': typeof DjBoekenSpijkenisseRoute
  '/dj-boeken-strijen': typeof DjBoekenStrijenRoute
  '/dj-boeken-strijensas': typeof DjBoekenStrijensasRoute
  '/dj-boeken-tiel': typeof DjBoekenTielRoute
  '/dj-boeken-tiengemeten': typeof DjBoekenTiengemetenRoute
  '/dj-boeken-tilburg': typeof DjBoekenTilburgRoute
  '/dj-boeken-tuil': typeof DjBoekenTuilRoute
  '/dj-boeken-utrecht': typeof DjBoekenUtrechtRoute
  '/dj-boeken-varik': typeof DjBoekenVarikRoute
  '/dj-boeken-veenendaal': typeof DjBoekenVeenendaalRoute
  '/dj-boeken-venlo': typeof DjBoekenVenloRoute
  '/dj-boeken-vlaardingen': typeof DjBoekenVlaardingenRoute
  '/dj-boeken-wageningen': typeof DjBoekenWageningenRoute
  '/dj-boeken-westmaas': typeof DjBoekenWestmaasRoute
  '/dj-boeken-zaltbommel': typeof DjBoekenZaltbommelRoute
  '/dj-boeken-zeist': typeof DjBoekenZeistRoute
  '/dj-boeken-zoetermeer': typeof DjBoekenZoetermeerRoute
  '/dj-boeken-zuid-beijerland': typeof DjBoekenZuidBeijerlandRoute
  '/dj-boeken-zuid-holland': typeof DjBoekenZuidHollandRoute
  '/dj-boeken-zwijndrecht': typeof DjBoekenZwijndrechtRoute
  '/dj-boeken-zwolle': typeof DjBoekenZwolleRoute
  '/dj-en-mc': typeof DjEnMcRoute
  '/feest-op-locatie': typeof FeestOpLocatieRoute
  '/festival-dj': typeof FestivalDjRoute
  '/horeca': typeof HorecaRoute
  '/personeelsfeest-dj': typeof PersoneelsfeestDjRoute
  '/prijzen': typeof PrijzenRoute
  '/privacy': typeof PrivacyRoute
  '/regios': typeof RegiosRoute
  '/reviews': typeof ReviewsRoute
  '/tuinfeest': typeof TuinfeestRoute
  '/verjaardag-dj': typeof VerjaardagDjRoute
  '/verzoekje': typeof VerzoekjeRoute
  '/werkwijze': typeof WerkwijzeRoute
  '/zakelijk-dj': typeof ZakelijkDjRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/artiesten': typeof ArtiestenRoute
  '/biografie': typeof BiografieRoute
  '/bruiloft-dj': typeof BruiloftDjRoute
  '/bruiloft-dj-betuwe': typeof BruiloftDjBetuweRoute
  '/bruiloft-dj-dordrecht': typeof BruiloftDjDordrechtRoute
  '/bruiloft-dj-hoeksche-waard': typeof BruiloftDjHoekscheWaardRoute
  '/bruiloft-dj-rotterdam': typeof BruiloftDjRotterdamRoute
  '/bruiloft-dj-tiel': typeof BruiloftDjTielRoute
  '/contact': typeof ContactRoute
  '/dj': typeof DjRoute
  '/dj-boeken-alblasserdam': typeof DjBoekenAlblasserdamRoute
  '/dj-boeken-albrandswaard': typeof DjBoekenAlbrandswaardRoute
  '/dj-boeken-alkmaar': typeof DjBoekenAlkmaarRoute
  '/dj-boeken-almere': typeof DjBoekenAlmereRoute
  '/dj-boeken-alphen-aan-den-rijn': typeof DjBoekenAlphenAanDenRijnRoute
  '/dj-boeken-amersfoort': typeof DjBoekenAmersfoortRoute
  '/dj-boeken-amstelveen': typeof DjBoekenAmstelveenRoute
  '/dj-boeken-amsterdam': typeof DjBoekenAmsterdamRoute
  '/dj-boeken-apeldoorn': typeof DjBoekenApeldoornRoute
  '/dj-boeken-arnhem': typeof DjBoekenArnhemRoute
  '/dj-boeken-assen': typeof DjBoekenAssenRoute
  '/dj-boeken-barendrecht': typeof DjBoekenBarendrechtRoute
  '/dj-boeken-betuwe': typeof DjBoekenBetuweRoute
  '/dj-boeken-bommelerwaard': typeof DjBoekenBommelerwaardRoute
  '/dj-boeken-breda': typeof DjBoekenBredaRoute
  '/dj-boeken-buren': typeof DjBoekenBurenRoute
  '/dj-boeken-capelle-aan-den-ijssel': typeof DjBoekenCapelleAanDenIjsselRoute
  '/dj-boeken-cillaarshoek': typeof DjBoekenCillaarshoekRoute
  '/dj-boeken-culemborg': typeof DjBoekenCulemborgRoute
  '/dj-boeken-delft': typeof DjBoekenDelftRoute
  '/dj-boeken-den-bosch': typeof DjBoekenDenBoschRoute
  '/dj-boeken-den-haag': typeof DjBoekenDenHaagRoute
  '/dj-boeken-deventer': typeof DjBoekenDeventerRoute
  '/dj-boeken-dordrecht': typeof DjBoekenDordrechtRoute
  '/dj-boeken-ede': typeof DjBoekenEdeRoute
  '/dj-boeken-eindhoven': typeof DjBoekenEindhovenRoute
  '/dj-boeken-enschede': typeof DjBoekenEnschedeRoute
  '/dj-boeken-geldermalsen': typeof DjBoekenGeldermalsenRoute
  '/dj-boeken-gorcum': typeof DjBoekenGorcumRoute
  '/dj-boeken-gorinchem': typeof DjBoekenGorinchemRoute
  '/dj-boeken-gouda': typeof DjBoekenGoudaRoute
  '/dj-boeken-goudswaard': typeof DjBoekenGoudswaardRoute
  '/dj-boeken-groningen': typeof DjBoekenGroningenRoute
  '/dj-boeken-haarlem': typeof DjBoekenHaarlemRoute
  '/dj-boeken-hardinxveld-giessendam': typeof DjBoekenHardinxveldGiessendamRoute
  '/dj-boeken-heinenoord': typeof DjBoekenHeinenoordRoute
  '/dj-boeken-helmond': typeof DjBoekenHelmondRoute
  '/dj-boeken-hendrik-ido-ambacht': typeof DjBoekenHendrikIdoAmbachtRoute
  '/dj-boeken-hilversum': typeof DjBoekenHilversumRoute
  '/dj-boeken-hoeksche-waard': typeof DjBoekenHoekscheWaardRoute
  '/dj-boeken-houten': typeof DjBoekenHoutenRoute
  '/dj-boeken-klaaswaal': typeof DjBoekenKlaaswaalRoute
  '/dj-boeken-leerdam': typeof DjBoekenLeerdamRoute
  '/dj-boeken-leeuwarden': typeof DjBoekenLeeuwardenRoute
  '/dj-boeken-leiden': typeof DjBoekenLeidenRoute
  '/dj-boeken-maasdam': typeof DjBoekenMaasdamRoute
  '/dj-boeken-maastricht': typeof DjBoekenMaastrichtRoute
  '/dj-boeken-middelburg': typeof DjBoekenMiddelburgRoute
  '/dj-boeken-mijnsheerenland': typeof DjBoekenMijnsheerenlandRoute
  '/dj-boeken-nieuw-beijerland': typeof DjBoekenNieuwBeijerlandRoute
  '/dj-boeken-nieuwegein': typeof DjBoekenNieuwegeinRoute
  '/dj-boeken-nijmegen': typeof DjBoekenNijmegenRoute
  '/dj-boeken-numansdorp': typeof DjBoekenNumansdorpRoute
  '/dj-boeken-ophemert': typeof DjBoekenOphemertRoute
  '/dj-boeken-oss': typeof DjBoekenOssRoute
  '/dj-boeken-oud-beijerland': typeof DjBoekenOudBeijerlandRoute
  '/dj-boeken-papendrecht': typeof DjBoekenPapendrechtRoute
  '/dj-boeken-piershil': typeof DjBoekenPiershilRoute
  '/dj-boeken-poortugaal': typeof DjBoekenPoortugaalRoute
  '/dj-boeken-puttershoek': typeof DjBoekenPuttershoekRoute
  '/dj-boeken-rhoon': typeof DjBoekenRhoonRoute
  '/dj-boeken-ridderkerk': typeof DjBoekenRidderkerkRoute
  '/dj-boeken-rivierenland': typeof DjBoekenRivierenlandRoute
  '/dj-boeken-roermond': typeof DjBoekenRoermondRoute
  '/dj-boeken-rotterdam': typeof DjBoekenRotterdamRoute
  '/dj-boeken-s-gravendeel': typeof DjBoekenSGravendeelRoute
  '/dj-boeken-schiedam': typeof DjBoekenSchiedamRoute
  '/dj-boeken-sliedrecht': typeof DjBoekenSliedrechtRoute
  '/dj-boeken-spijkenisse': typeof DjBoekenSpijkenisseRoute
  '/dj-boeken-strijen': typeof DjBoekenStrijenRoute
  '/dj-boeken-strijensas': typeof DjBoekenStrijensasRoute
  '/dj-boeken-tiel': typeof DjBoekenTielRoute
  '/dj-boeken-tiengemeten': typeof DjBoekenTiengemetenRoute
  '/dj-boeken-tilburg': typeof DjBoekenTilburgRoute
  '/dj-boeken-tuil': typeof DjBoekenTuilRoute
  '/dj-boeken-utrecht': typeof DjBoekenUtrechtRoute
  '/dj-boeken-varik': typeof DjBoekenVarikRoute
  '/dj-boeken-veenendaal': typeof DjBoekenVeenendaalRoute
  '/dj-boeken-venlo': typeof DjBoekenVenloRoute
  '/dj-boeken-vlaardingen': typeof DjBoekenVlaardingenRoute
  '/dj-boeken-wageningen': typeof DjBoekenWageningenRoute
  '/dj-boeken-westmaas': typeof DjBoekenWestmaasRoute
  '/dj-boeken-zaltbommel': typeof DjBoekenZaltbommelRoute
  '/dj-boeken-zeist': typeof DjBoekenZeistRoute
  '/dj-boeken-zoetermeer': typeof DjBoekenZoetermeerRoute
  '/dj-boeken-zuid-beijerland': typeof DjBoekenZuidBeijerlandRoute
  '/dj-boeken-zuid-holland': typeof DjBoekenZuidHollandRoute
  '/dj-boeken-zwijndrecht': typeof DjBoekenZwijndrechtRoute
  '/dj-boeken-zwolle': typeof DjBoekenZwolleRoute
  '/dj-en-mc': typeof DjEnMcRoute
  '/feest-op-locatie': typeof FeestOpLocatieRoute
  '/festival-dj': typeof FestivalDjRoute
  '/horeca': typeof HorecaRoute
  '/personeelsfeest-dj': typeof PersoneelsfeestDjRoute
  '/prijzen': typeof PrijzenRoute
  '/privacy': typeof PrivacyRoute
  '/regios': typeof RegiosRoute
  '/reviews': typeof ReviewsRoute
  '/tuinfeest': typeof TuinfeestRoute
  '/verjaardag-dj': typeof VerjaardagDjRoute
  '/verzoekje': typeof VerzoekjeRoute
  '/werkwijze': typeof WerkwijzeRoute
  '/zakelijk-dj': typeof ZakelijkDjRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/algemene-voorwaarden'
    | '/artiesten'
    | '/biografie'
    | '/bruiloft-dj'
    | '/bruiloft-dj-betuwe'
    | '/bruiloft-dj-dordrecht'
    | '/bruiloft-dj-hoeksche-waard'
    | '/bruiloft-dj-rotterdam'
    | '/bruiloft-dj-tiel'
    | '/contact'
    | '/dj'
    | '/dj-boeken-alblasserdam'
    | '/dj-boeken-albrandswaard'
    | '/dj-boeken-alkmaar'
    | '/dj-boeken-almere'
    | '/dj-boeken-alphen-aan-den-rijn'
    | '/dj-boeken-amersfoort'
    | '/dj-boeken-amstelveen'
    | '/dj-boeken-amsterdam'
    | '/dj-boeken-apeldoorn'
    | '/dj-boeken-arnhem'
    | '/dj-boeken-assen'
    | '/dj-boeken-barendrecht'
    | '/dj-boeken-betuwe'
    | '/dj-boeken-bommelerwaard'
    | '/dj-boeken-breda'
    | '/dj-boeken-buren'
    | '/dj-boeken-capelle-aan-den-ijssel'
    | '/dj-boeken-cillaarshoek'
    | '/dj-boeken-culemborg'
    | '/dj-boeken-delft'
    | '/dj-boeken-den-bosch'
    | '/dj-boeken-den-haag'
    | '/dj-boeken-deventer'
    | '/dj-boeken-dordrecht'
    | '/dj-boeken-ede'
    | '/dj-boeken-eindhoven'
    | '/dj-boeken-enschede'
    | '/dj-boeken-geldermalsen'
    | '/dj-boeken-gorcum'
    | '/dj-boeken-gorinchem'
    | '/dj-boeken-gouda'
    | '/dj-boeken-goudswaard'
    | '/dj-boeken-groningen'
    | '/dj-boeken-haarlem'
    | '/dj-boeken-hardinxveld-giessendam'
    | '/dj-boeken-heinenoord'
    | '/dj-boeken-helmond'
    | '/dj-boeken-hendrik-ido-ambacht'
    | '/dj-boeken-hilversum'
    | '/dj-boeken-hoeksche-waard'
    | '/dj-boeken-houten'
    | '/dj-boeken-klaaswaal'
    | '/dj-boeken-leerdam'
    | '/dj-boeken-leeuwarden'
    | '/dj-boeken-leiden'
    | '/dj-boeken-maasdam'
    | '/dj-boeken-maastricht'
    | '/dj-boeken-middelburg'
    | '/dj-boeken-mijnsheerenland'
    | '/dj-boeken-nieuw-beijerland'
    | '/dj-boeken-nieuwegein'
    | '/dj-boeken-nijmegen'
    | '/dj-boeken-numansdorp'
    | '/dj-boeken-ophemert'
    | '/dj-boeken-oss'
    | '/dj-boeken-oud-beijerland'
    | '/dj-boeken-papendrecht'
    | '/dj-boeken-piershil'
    | '/dj-boeken-poortugaal'
    | '/dj-boeken-puttershoek'
    | '/dj-boeken-rhoon'
    | '/dj-boeken-ridderkerk'
    | '/dj-boeken-rivierenland'
    | '/dj-boeken-roermond'
    | '/dj-boeken-rotterdam'
    | '/dj-boeken-s-gravendeel'
    | '/dj-boeken-schiedam'
    | '/dj-boeken-sliedrecht'
    | '/dj-boeken-spijkenisse'
    | '/dj-boeken-strijen'
    | '/dj-boeken-strijensas'
    | '/dj-boeken-tiel'
    | '/dj-boeken-tiengemeten'
    | '/dj-boeken-tilburg'
    | '/dj-boeken-tuil'
    | '/dj-boeken-utrecht'
    | '/dj-boeken-varik'
    | '/dj-boeken-veenendaal'
    | '/dj-boeken-venlo'
    | '/dj-boeken-vlaardingen'
    | '/dj-boeken-wageningen'
    | '/dj-boeken-westmaas'
    | '/dj-boeken-zaltbommel'
    | '/dj-boeken-zeist'
    | '/dj-boeken-zoetermeer'
    | '/dj-boeken-zuid-beijerland'
    | '/dj-boeken-zuid-holland'
    | '/dj-boeken-zwijndrecht'
    | '/dj-boeken-zwolle'
    | '/dj-en-mc'
    | '/feest-op-locatie'
    | '/festival-dj'
    | '/horeca'
    | '/personeelsfeest-dj'
    | '/prijzen'
    | '/privacy'
    | '/regios'
    | '/reviews'
    | '/tuinfeest'
    | '/verjaardag-dj'
    | '/verzoekje'
    | '/werkwijze'
    | '/zakelijk-dj'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/algemene-voorwaarden'
    | '/artiesten'
    | '/biografie'
    | '/bruiloft-dj'
    | '/bruiloft-dj-betuwe'
    | '/bruiloft-dj-dordrecht'
    | '/bruiloft-dj-hoeksche-waard'
    | '/bruiloft-dj-rotterdam'
    | '/bruiloft-dj-tiel'
    | '/contact'
    | '/dj'
    | '/dj-boeken-alblasserdam'
    | '/dj-boeken-albrandswaard'
    | '/dj-boeken-alkmaar'
    | '/dj-boeken-almere'
    | '/dj-boeken-alphen-aan-den-rijn'
    | '/dj-boeken-amersfoort'
    | '/dj-boeken-amstelveen'
    | '/dj-boeken-amsterdam'
    | '/dj-boeken-apeldoorn'
    | '/dj-boeken-arnhem'
    | '/dj-boeken-assen'
    | '/dj-boeken-barendrecht'
    | '/dj-boeken-betuwe'
    | '/dj-boeken-bommelerwaard'
    | '/dj-boeken-breda'
    | '/dj-boeken-buren'
    | '/dj-boeken-capelle-aan-den-ijssel'
    | '/dj-boeken-cillaarshoek'
    | '/dj-boeken-culemborg'
    | '/dj-boeken-delft'
    | '/dj-boeken-den-bosch'
    | '/dj-boeken-den-haag'
    | '/dj-boeken-deventer'
    | '/dj-boeken-dordrecht'
    | '/dj-boeken-ede'
    | '/dj-boeken-eindhoven'
    | '/dj-boeken-enschede'
    | '/dj-boeken-geldermalsen'
    | '/dj-boeken-gorcum'
    | '/dj-boeken-gorinchem'
    | '/dj-boeken-gouda'
    | '/dj-boeken-goudswaard'
    | '/dj-boeken-groningen'
    | '/dj-boeken-haarlem'
    | '/dj-boeken-hardinxveld-giessendam'
    | '/dj-boeken-heinenoord'
    | '/dj-boeken-helmond'
    | '/dj-boeken-hendrik-ido-ambacht'
    | '/dj-boeken-hilversum'
    | '/dj-boeken-hoeksche-waard'
    | '/dj-boeken-houten'
    | '/dj-boeken-klaaswaal'
    | '/dj-boeken-leerdam'
    | '/dj-boeken-leeuwarden'
    | '/dj-boeken-leiden'
    | '/dj-boeken-maasdam'
    | '/dj-boeken-maastricht'
    | '/dj-boeken-middelburg'
    | '/dj-boeken-mijnsheerenland'
    | '/dj-boeken-nieuw-beijerland'
    | '/dj-boeken-nieuwegein'
    | '/dj-boeken-nijmegen'
    | '/dj-boeken-numansdorp'
    | '/dj-boeken-ophemert'
    | '/dj-boeken-oss'
    | '/dj-boeken-oud-beijerland'
    | '/dj-boeken-papendrecht'
    | '/dj-boeken-piershil'
    | '/dj-boeken-poortugaal'
    | '/dj-boeken-puttershoek'
    | '/dj-boeken-rhoon'
    | '/dj-boeken-ridderkerk'
    | '/dj-boeken-rivierenland'
    | '/dj-boeken-roermond'
    | '/dj-boeken-rotterdam'
    | '/dj-boeken-s-gravendeel'
    | '/dj-boeken-schiedam'
    | '/dj-boeken-sliedrecht'
    | '/dj-boeken-spijkenisse'
    | '/dj-boeken-strijen'
    | '/dj-boeken-strijensas'
    | '/dj-boeken-tiel'
    | '/dj-boeken-tiengemeten'
    | '/dj-boeken-tilburg'
    | '/dj-boeken-tuil'
    | '/dj-boeken-utrecht'
    | '/dj-boeken-varik'
    | '/dj-boeken-veenendaal'
    | '/dj-boeken-venlo'
    | '/dj-boeken-vlaardingen'
    | '/dj-boeken-wageningen'
    | '/dj-boeken-westmaas'
    | '/dj-boeken-zaltbommel'
    | '/dj-boeken-zeist'
    | '/dj-boeken-zoetermeer'
    | '/dj-boeken-zuid-beijerland'
    | '/dj-boeken-zuid-holland'
    | '/dj-boeken-zwijndrecht'
    | '/dj-boeken-zwolle'
    | '/dj-en-mc'
    | '/feest-op-locatie'
    | '/festival-dj'
    | '/horeca'
    | '/personeelsfeest-dj'
    | '/prijzen'
    | '/privacy'
    | '/regios'
    | '/reviews'
    | '/tuinfeest'
    | '/verjaardag-dj'
    | '/verzoekje'
    | '/werkwijze'
    | '/zakelijk-dj'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/algemene-voorwaarden'
    | '/artiesten'
    | '/biografie'
    | '/bruiloft-dj'
    | '/bruiloft-dj-betuwe'
    | '/bruiloft-dj-dordrecht'
    | '/bruiloft-dj-hoeksche-waard'
    | '/bruiloft-dj-rotterdam'
    | '/bruiloft-dj-tiel'
    | '/contact'
    | '/dj'
    | '/dj-boeken-alblasserdam'
    | '/dj-boeken-albrandswaard'
    | '/dj-boeken-alkmaar'
    | '/dj-boeken-almere'
    | '/dj-boeken-alphen-aan-den-rijn'
    | '/dj-boeken-amersfoort'
    | '/dj-boeken-amstelveen'
    | '/dj-boeken-amsterdam'
    | '/dj-boeken-apeldoorn'
    | '/dj-boeken-arnhem'
    | '/dj-boeken-assen'
    | '/dj-boeken-barendrecht'
    | '/dj-boeken-betuwe'
    | '/dj-boeken-bommelerwaard'
    | '/dj-boeken-breda'
    | '/dj-boeken-buren'
    | '/dj-boeken-capelle-aan-den-ijssel'
    | '/dj-boeken-cillaarshoek'
    | '/dj-boeken-culemborg'
    | '/dj-boeken-delft'
    | '/dj-boeken-den-bosch'
    | '/dj-boeken-den-haag'
    | '/dj-boeken-deventer'
    | '/dj-boeken-dordrecht'
    | '/dj-boeken-ede'
    | '/dj-boeken-eindhoven'
    | '/dj-boeken-enschede'
    | '/dj-boeken-geldermalsen'
    | '/dj-boeken-gorcum'
    | '/dj-boeken-gorinchem'
    | '/dj-boeken-gouda'
    | '/dj-boeken-goudswaard'
    | '/dj-boeken-groningen'
    | '/dj-boeken-haarlem'
    | '/dj-boeken-hardinxveld-giessendam'
    | '/dj-boeken-heinenoord'
    | '/dj-boeken-helmond'
    | '/dj-boeken-hendrik-ido-ambacht'
    | '/dj-boeken-hilversum'
    | '/dj-boeken-hoeksche-waard'
    | '/dj-boeken-houten'
    | '/dj-boeken-klaaswaal'
    | '/dj-boeken-leerdam'
    | '/dj-boeken-leeuwarden'
    | '/dj-boeken-leiden'
    | '/dj-boeken-maasdam'
    | '/dj-boeken-maastricht'
    | '/dj-boeken-middelburg'
    | '/dj-boeken-mijnsheerenland'
    | '/dj-boeken-nieuw-beijerland'
    | '/dj-boeken-nieuwegein'
    | '/dj-boeken-nijmegen'
    | '/dj-boeken-numansdorp'
    | '/dj-boeken-ophemert'
    | '/dj-boeken-oss'
    | '/dj-boeken-oud-beijerland'
    | '/dj-boeken-papendrecht'
    | '/dj-boeken-piershil'
    | '/dj-boeken-poortugaal'
    | '/dj-boeken-puttershoek'
    | '/dj-boeken-rhoon'
    | '/dj-boeken-ridderkerk'
    | '/dj-boeken-rivierenland'
    | '/dj-boeken-roermond'
    | '/dj-boeken-rotterdam'
    | '/dj-boeken-s-gravendeel'
    | '/dj-boeken-schiedam'
    | '/dj-boeken-sliedrecht'
    | '/dj-boeken-spijkenisse'
    | '/dj-boeken-strijen'
    | '/dj-boeken-strijensas'
    | '/dj-boeken-tiel'
    | '/dj-boeken-tiengemeten'
    | '/dj-boeken-tilburg'
    | '/dj-boeken-tuil'
    | '/dj-boeken-utrecht'
    | '/dj-boeken-varik'
    | '/dj-boeken-veenendaal'
    | '/dj-boeken-venlo'
    | '/dj-boeken-vlaardingen'
    | '/dj-boeken-wageningen'
    | '/dj-boeken-westmaas'
    | '/dj-boeken-zaltbommel'
    | '/dj-boeken-zeist'
    | '/dj-boeken-zoetermeer'
    | '/dj-boeken-zuid-beijerland'
    | '/dj-boeken-zuid-holland'
    | '/dj-boeken-zwijndrecht'
    | '/dj-boeken-zwolle'
    | '/dj-en-mc'
    | '/feest-op-locatie'
    | '/festival-dj'
    | '/horeca'
    | '/personeelsfeest-dj'
    | '/prijzen'
    | '/privacy'
    | '/regios'
    | '/reviews'
    | '/tuinfeest'
    | '/verjaardag-dj'
    | '/verzoekje'
    | '/werkwijze'
    | '/zakelijk-dj'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlgemeneVoorwaardenRoute: typeof AlgemeneVoorwaardenRoute
  ArtiestenRoute: typeof ArtiestenRoute
  BiografieRoute: typeof BiografieRoute
  BruiloftDjRoute: typeof BruiloftDjRoute
  BruiloftDjBetuweRoute: typeof BruiloftDjBetuweRoute
  BruiloftDjDordrechtRoute: typeof BruiloftDjDordrechtRoute
  BruiloftDjHoekscheWaardRoute: typeof BruiloftDjHoekscheWaardRoute
  BruiloftDjRotterdamRoute: typeof BruiloftDjRotterdamRoute
  BruiloftDjTielRoute: typeof BruiloftDjTielRoute
  ContactRoute: typeof ContactRoute
  DjRoute: typeof DjRoute
  DjBoekenAlblasserdamRoute: typeof DjBoekenAlblasserdamRoute
  DjBoekenAlbrandswaardRoute: typeof DjBoekenAlbrandswaardRoute
  DjBoekenAlkmaarRoute: typeof DjBoekenAlkmaarRoute
  DjBoekenAlmereRoute: typeof DjBoekenAlmereRoute
  DjBoekenAlphenAanDenRijnRoute: typeof DjBoekenAlphenAanDenRijnRoute
  DjBoekenAmersfoortRoute: typeof DjBoekenAmersfoortRoute
  DjBoekenAmstelveenRoute: typeof DjBoekenAmstelveenRoute
  DjBoekenAmsterdamRoute: typeof DjBoekenAmsterdamRoute
  DjBoekenApeldoornRoute: typeof DjBoekenApeldoornRoute
  DjBoekenArnhemRoute: typeof DjBoekenArnhemRoute
  DjBoekenAssenRoute: typeof DjBoekenAssenRoute
  DjBoekenBarendrechtRoute: typeof DjBoekenBarendrechtRoute
  DjBoekenBetuweRoute: typeof DjBoekenBetuweRoute
  DjBoekenBommelerwaardRoute: typeof DjBoekenBommelerwaardRoute
  DjBoekenBredaRoute: typeof DjBoekenBredaRoute
  DjBoekenBurenRoute: typeof DjBoekenBurenRoute
  DjBoekenCapelleAanDenIjsselRoute: typeof DjBoekenCapelleAanDenIjsselRoute
  DjBoekenCillaarshoekRoute: typeof DjBoekenCillaarshoekRoute
  DjBoekenCulemborgRoute: typeof DjBoekenCulemborgRoute
  DjBoekenDelftRoute: typeof DjBoekenDelftRoute
  DjBoekenDenBoschRoute: typeof DjBoekenDenBoschRoute
  DjBoekenDenHaagRoute: typeof DjBoekenDenHaagRoute
  DjBoekenDeventerRoute: typeof DjBoekenDeventerRoute
  DjBoekenDordrechtRoute: typeof DjBoekenDordrechtRoute
  DjBoekenEdeRoute: typeof DjBoekenEdeRoute
  DjBoekenEindhovenRoute: typeof DjBoekenEindhovenRoute
  DjBoekenEnschedeRoute: typeof DjBoekenEnschedeRoute
  DjBoekenGeldermalsenRoute: typeof DjBoekenGeldermalsenRoute
  DjBoekenGorcumRoute: typeof DjBoekenGorcumRoute
  DjBoekenGorinchemRoute: typeof DjBoekenGorinchemRoute
  DjBoekenGoudaRoute: typeof DjBoekenGoudaRoute
  DjBoekenGoudswaardRoute: typeof DjBoekenGoudswaardRoute
  DjBoekenGroningenRoute: typeof DjBoekenGroningenRoute
  DjBoekenHaarlemRoute: typeof DjBoekenHaarlemRoute
  DjBoekenHardinxveldGiessendamRoute: typeof DjBoekenHardinxveldGiessendamRoute
  DjBoekenHeinenoordRoute: typeof DjBoekenHeinenoordRoute
  DjBoekenHelmondRoute: typeof DjBoekenHelmondRoute
  DjBoekenHendrikIdoAmbachtRoute: typeof DjBoekenHendrikIdoAmbachtRoute
  DjBoekenHilversumRoute: typeof DjBoekenHilversumRoute
  DjBoekenHoekscheWaardRoute: typeof DjBoekenHoekscheWaardRoute
  DjBoekenHoutenRoute: typeof DjBoekenHoutenRoute
  DjBoekenKlaaswaalRoute: typeof DjBoekenKlaaswaalRoute
  DjBoekenLeerdamRoute: typeof DjBoekenLeerdamRoute
  DjBoekenLeeuwardenRoute: typeof DjBoekenLeeuwardenRoute
  DjBoekenLeidenRoute: typeof DjBoekenLeidenRoute
  DjBoekenMaasdamRoute: typeof DjBoekenMaasdamRoute
  DjBoekenMaastrichtRoute: typeof DjBoekenMaastrichtRoute
  DjBoekenMiddelburgRoute: typeof DjBoekenMiddelburgRoute
  DjBoekenMijnsheerenlandRoute: typeof DjBoekenMijnsheerenlandRoute
  DjBoekenNieuwBeijerlandRoute: typeof DjBoekenNieuwBeijerlandRoute
  DjBoekenNieuwegeinRoute: typeof DjBoekenNieuwegeinRoute
  DjBoekenNijmegenRoute: typeof DjBoekenNijmegenRoute
  DjBoekenNumansdorpRoute: typeof DjBoekenNumansdorpRoute
  DjBoekenOphemertRoute: typeof DjBoekenOphemertRoute
  DjBoekenOssRoute: typeof DjBoekenOssRoute
  DjBoekenOudBeijerlandRoute: typeof DjBoekenOudBeijerlandRoute
  DjBoekenPapendrechtRoute: typeof DjBoekenPapendrechtRoute
  DjBoekenPiershilRoute: typeof DjBoekenPiershilRoute
  DjBoekenPoortugaalRoute: typeof DjBoekenPoortugaalRoute
  DjBoekenPuttershoekRoute: typeof DjBoekenPuttershoekRoute
  DjBoekenRhoonRoute: typeof DjBoekenRhoonRoute
  DjBoekenRidderkerkRoute: typeof DjBoekenRidderkerkRoute
  DjBoekenRivierenlandRoute: typeof DjBoekenRivierenlandRoute
  DjBoekenRoermondRoute: typeof DjBoekenRoermondRoute
  DjBoekenRotterdamRoute: typeof DjBoekenRotterdamRoute
  DjBoekenSGravendeelRoute: typeof DjBoekenSGravendeelRoute
  DjBoekenSchiedamRoute: typeof DjBoekenSchiedamRoute
  DjBoekenSliedrechtRoute: typeof DjBoekenSliedrechtRoute
  DjBoekenSpijkenisseRoute: typeof DjBoekenSpijkenisseRoute
  DjBoekenStrijenRoute: typeof DjBoekenStrijenRoute
  DjBoekenStrijensasRoute: typeof DjBoekenStrijensasRoute
  DjBoekenTielRoute: typeof DjBoekenTielRoute
  DjBoekenTiengemetenRoute: typeof DjBoekenTiengemetenRoute
  DjBoekenTilburgRoute: typeof DjBoekenTilburgRoute
  DjBoekenTuilRoute: typeof DjBoekenTuilRoute
  DjBoekenUtrechtRoute: typeof DjBoekenUtrechtRoute
  DjBoekenVarikRoute: typeof DjBoekenVarikRoute
  DjBoekenVeenendaalRoute: typeof DjBoekenVeenendaalRoute
  DjBoekenVenloRoute: typeof DjBoekenVenloRoute
  DjBoekenVlaardingenRoute: typeof DjBoekenVlaardingenRoute
  DjBoekenWageningenRoute: typeof DjBoekenWageningenRoute
  DjBoekenWestmaasRoute: typeof DjBoekenWestmaasRoute
  DjBoekenZaltbommelRoute: typeof DjBoekenZaltbommelRoute
  DjBoekenZeistRoute: typeof DjBoekenZeistRoute
  DjBoekenZoetermeerRoute: typeof DjBoekenZoetermeerRoute
  DjBoekenZuidBeijerlandRoute: typeof DjBoekenZuidBeijerlandRoute
  DjBoekenZuidHollandRoute: typeof DjBoekenZuidHollandRoute
  DjBoekenZwijndrechtRoute: typeof DjBoekenZwijndrechtRoute
  DjBoekenZwolleRoute: typeof DjBoekenZwolleRoute
  DjEnMcRoute: typeof DjEnMcRoute
  FeestOpLocatieRoute: typeof FeestOpLocatieRoute
  FestivalDjRoute: typeof FestivalDjRoute
  HorecaRoute: typeof HorecaRoute
  PersoneelsfeestDjRoute: typeof PersoneelsfeestDjRoute
  PrijzenRoute: typeof PrijzenRoute
  PrivacyRoute: typeof PrivacyRoute
  RegiosRoute: typeof RegiosRoute
  ReviewsRoute: typeof ReviewsRoute
  TuinfeestRoute: typeof TuinfeestRoute
  VerjaardagDjRoute: typeof VerjaardagDjRoute
  VerzoekjeRoute: typeof VerzoekjeRoute
  WerkwijzeRoute: typeof WerkwijzeRoute
  ZakelijkDjRoute: typeof ZakelijkDjRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zakelijk-dj': {
      id: '/zakelijk-dj'
      path: '/zakelijk-dj'
      fullPath: '/zakelijk-dj'
      preLoaderRoute: typeof ZakelijkDjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/werkwijze': {
      id: '/werkwijze'
      path: '/werkwijze'
      fullPath: '/werkwijze'
      preLoaderRoute: typeof WerkwijzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verzoekje': {
      id: '/verzoekje'
      path: '/verzoekje'
      fullPath: '/verzoekje'
      preLoaderRoute: typeof VerzoekjeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verjaardag-dj': {
      id: '/verjaardag-dj'
      path: '/verjaardag-dj'
      fullPath: '/verjaardag-dj'
      preLoaderRoute: typeof VerjaardagDjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tuinfeest': {
      id: '/tuinfeest'
      path: '/tuinfeest'
      fullPath: '/tuinfeest'
      preLoaderRoute: typeof TuinfeestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regios': {
      id: '/regios'
      path: '/regios'
      fullPath: '/regios'
      preLoaderRoute: typeof RegiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prijzen': {
      id: '/prijzen'
      path: '/prijzen'
      fullPath: '/prijzen'
      preLoaderRoute: typeof PrijzenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personeelsfeest-dj': {
      id: '/personeelsfeest-dj'
      path: '/personeelsfeest-dj'
      fullPath: '/personeelsfeest-dj'
      preLoaderRoute: typeof PersoneelsfeestDjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horeca': {
      id: '/horeca'
      path: '/horeca'
      fullPath: '/horeca'
      preLoaderRoute: typeof HorecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festival-dj': {
      id: '/festival-dj'
      path: '/festival-dj'
      fullPath: '/festival-dj'
      preLoaderRoute: typeof FestivalDjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feest-op-locatie': {
      id: '/feest-op-locatie'
      path: '/feest-op-locatie'
      fullPath: '/feest-op-locatie'
      preLoaderRoute: typeof FeestOpLocatieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-en-mc': {
      id: '/dj-en-mc'
      path: '/dj-en-mc'
      fullPath: '/dj-en-mc'
      preLoaderRoute: typeof DjEnMcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-zwolle': {
      id: '/dj-boeken-zwolle'
      path: '/dj-boeken-zwolle'
      fullPath: '/dj-boeken-zwolle'
      preLoaderRoute: typeof DjBoekenZwolleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-zwijndrecht': {
      id: '/dj-boeken-zwijndrecht'
      path: '/dj-boeken-zwijndrecht'
      fullPath: '/dj-boeken-zwijndrecht'
      preLoaderRoute: typeof DjBoekenZwijndrechtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-zuid-holland': {
      id: '/dj-boeken-zuid-holland'
      path: '/dj-boeken-zuid-holland'
      fullPath: '/dj-boeken-zuid-holland'
      preLoaderRoute: typeof DjBoekenZuidHollandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-zuid-beijerland': {
      id: '/dj-boeken-zuid-beijerland'
      path: '/dj-boeken-zuid-beijerland'
      fullPath: '/dj-boeken-zuid-beijerland'
      preLoaderRoute: typeof DjBoekenZuidBeijerlandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-zoetermeer': {
      id: '/dj-boeken-zoetermeer'
      path: '/dj-boeken-zoetermeer'
      fullPath: '/dj-boeken-zoetermeer'
      preLoaderRoute: typeof DjBoekenZoetermeerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-zeist': {
      id: '/dj-boeken-zeist'
      path: '/dj-boeken-zeist'
      fullPath: '/dj-boeken-zeist'
      preLoaderRoute: typeof DjBoekenZeistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-zaltbommel': {
      id: '/dj-boeken-zaltbommel'
      path: '/dj-boeken-zaltbommel'
      fullPath: '/dj-boeken-zaltbommel'
      preLoaderRoute: typeof DjBoekenZaltbommelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-westmaas': {
      id: '/dj-boeken-westmaas'
      path: '/dj-boeken-westmaas'
      fullPath: '/dj-boeken-westmaas'
      preLoaderRoute: typeof DjBoekenWestmaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-wageningen': {
      id: '/dj-boeken-wageningen'
      path: '/dj-boeken-wageningen'
      fullPath: '/dj-boeken-wageningen'
      preLoaderRoute: typeof DjBoekenWageningenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-vlaardingen': {
      id: '/dj-boeken-vlaardingen'
      path: '/dj-boeken-vlaardingen'
      fullPath: '/dj-boeken-vlaardingen'
      preLoaderRoute: typeof DjBoekenVlaardingenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-venlo': {
      id: '/dj-boeken-venlo'
      path: '/dj-boeken-venlo'
      fullPath: '/dj-boeken-venlo'
      preLoaderRoute: typeof DjBoekenVenloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-veenendaal': {
      id: '/dj-boeken-veenendaal'
      path: '/dj-boeken-veenendaal'
      fullPath: '/dj-boeken-veenendaal'
      preLoaderRoute: typeof DjBoekenVeenendaalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-varik': {
      id: '/dj-boeken-varik'
      path: '/dj-boeken-varik'
      fullPath: '/dj-boeken-varik'
      preLoaderRoute: typeof DjBoekenVarikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-utrecht': {
      id: '/dj-boeken-utrecht'
      path: '/dj-boeken-utrecht'
      fullPath: '/dj-boeken-utrecht'
      preLoaderRoute: typeof DjBoekenUtrechtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-tuil': {
      id: '/dj-boeken-tuil'
      path: '/dj-boeken-tuil'
      fullPath: '/dj-boeken-tuil'
      preLoaderRoute: typeof DjBoekenTuilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-tilburg': {
      id: '/dj-boeken-tilburg'
      path: '/dj-boeken-tilburg'
      fullPath: '/dj-boeken-tilburg'
      preLoaderRoute: typeof DjBoekenTilburgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-tiengemeten': {
      id: '/dj-boeken-tiengemeten'
      path: '/dj-boeken-tiengemeten'
      fullPath: '/dj-boeken-tiengemeten'
      preLoaderRoute: typeof DjBoekenTiengemetenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-tiel': {
      id: '/dj-boeken-tiel'
      path: '/dj-boeken-tiel'
      fullPath: '/dj-boeken-tiel'
      preLoaderRoute: typeof DjBoekenTielRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-strijensas': {
      id: '/dj-boeken-strijensas'
      path: '/dj-boeken-strijensas'
      fullPath: '/dj-boeken-strijensas'
      preLoaderRoute: typeof DjBoekenStrijensasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-strijen': {
      id: '/dj-boeken-strijen'
      path: '/dj-boeken-strijen'
      fullPath: '/dj-boeken-strijen'
      preLoaderRoute: typeof DjBoekenStrijenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-spijkenisse': {
      id: '/dj-boeken-spijkenisse'
      path: '/dj-boeken-spijkenisse'
      fullPath: '/dj-boeken-spijkenisse'
      preLoaderRoute: typeof DjBoekenSpijkenisseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-sliedrecht': {
      id: '/dj-boeken-sliedrecht'
      path: '/dj-boeken-sliedrecht'
      fullPath: '/dj-boeken-sliedrecht'
      preLoaderRoute: typeof DjBoekenSliedrechtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-schiedam': {
      id: '/dj-boeken-schiedam'
      path: '/dj-boeken-schiedam'
      fullPath: '/dj-boeken-schiedam'
      preLoaderRoute: typeof DjBoekenSchiedamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-s-gravendeel': {
      id: '/dj-boeken-s-gravendeel'
      path: '/dj-boeken-s-gravendeel'
      fullPath: '/dj-boeken-s-gravendeel'
      preLoaderRoute: typeof DjBoekenSGravendeelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-rotterdam': {
      id: '/dj-boeken-rotterdam'
      path: '/dj-boeken-rotterdam'
      fullPath: '/dj-boeken-rotterdam'
      preLoaderRoute: typeof DjBoekenRotterdamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-roermond': {
      id: '/dj-boeken-roermond'
      path: '/dj-boeken-roermond'
      fullPath: '/dj-boeken-roermond'
      preLoaderRoute: typeof DjBoekenRoermondRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-rivierenland': {
      id: '/dj-boeken-rivierenland'
      path: '/dj-boeken-rivierenland'
      fullPath: '/dj-boeken-rivierenland'
      preLoaderRoute: typeof DjBoekenRivierenlandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-ridderkerk': {
      id: '/dj-boeken-ridderkerk'
      path: '/dj-boeken-ridderkerk'
      fullPath: '/dj-boeken-ridderkerk'
      preLoaderRoute: typeof DjBoekenRidderkerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-rhoon': {
      id: '/dj-boeken-rhoon'
      path: '/dj-boeken-rhoon'
      fullPath: '/dj-boeken-rhoon'
      preLoaderRoute: typeof DjBoekenRhoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-puttershoek': {
      id: '/dj-boeken-puttershoek'
      path: '/dj-boeken-puttershoek'
      fullPath: '/dj-boeken-puttershoek'
      preLoaderRoute: typeof DjBoekenPuttershoekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-poortugaal': {
      id: '/dj-boeken-poortugaal'
      path: '/dj-boeken-poortugaal'
      fullPath: '/dj-boeken-poortugaal'
      preLoaderRoute: typeof DjBoekenPoortugaalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-piershil': {
      id: '/dj-boeken-piershil'
      path: '/dj-boeken-piershil'
      fullPath: '/dj-boeken-piershil'
      preLoaderRoute: typeof DjBoekenPiershilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-papendrecht': {
      id: '/dj-boeken-papendrecht'
      path: '/dj-boeken-papendrecht'
      fullPath: '/dj-boeken-papendrecht'
      preLoaderRoute: typeof DjBoekenPapendrechtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-oud-beijerland': {
      id: '/dj-boeken-oud-beijerland'
      path: '/dj-boeken-oud-beijerland'
      fullPath: '/dj-boeken-oud-beijerland'
      preLoaderRoute: typeof DjBoekenOudBeijerlandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-oss': {
      id: '/dj-boeken-oss'
      path: '/dj-boeken-oss'
      fullPath: '/dj-boeken-oss'
      preLoaderRoute: typeof DjBoekenOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-ophemert': {
      id: '/dj-boeken-ophemert'
      path: '/dj-boeken-ophemert'
      fullPath: '/dj-boeken-ophemert'
      preLoaderRoute: typeof DjBoekenOphemertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-numansdorp': {
      id: '/dj-boeken-numansdorp'
      path: '/dj-boeken-numansdorp'
      fullPath: '/dj-boeken-numansdorp'
      preLoaderRoute: typeof DjBoekenNumansdorpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-nijmegen': {
      id: '/dj-boeken-nijmegen'
      path: '/dj-boeken-nijmegen'
      fullPath: '/dj-boeken-nijmegen'
      preLoaderRoute: typeof DjBoekenNijmegenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-nieuwegein': {
      id: '/dj-boeken-nieuwegein'
      path: '/dj-boeken-nieuwegein'
      fullPath: '/dj-boeken-nieuwegein'
      preLoaderRoute: typeof DjBoekenNieuwegeinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-nieuw-beijerland': {
      id: '/dj-boeken-nieuw-beijerland'
      path: '/dj-boeken-nieuw-beijerland'
      fullPath: '/dj-boeken-nieuw-beijerland'
      preLoaderRoute: typeof DjBoekenNieuwBeijerlandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-mijnsheerenland': {
      id: '/dj-boeken-mijnsheerenland'
      path: '/dj-boeken-mijnsheerenland'
      fullPath: '/dj-boeken-mijnsheerenland'
      preLoaderRoute: typeof DjBoekenMijnsheerenlandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-middelburg': {
      id: '/dj-boeken-middelburg'
      path: '/dj-boeken-middelburg'
      fullPath: '/dj-boeken-middelburg'
      preLoaderRoute: typeof DjBoekenMiddelburgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-maastricht': {
      id: '/dj-boeken-maastricht'
      path: '/dj-boeken-maastricht'
      fullPath: '/dj-boeken-maastricht'
      preLoaderRoute: typeof DjBoekenMaastrichtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-maasdam': {
      id: '/dj-boeken-maasdam'
      path: '/dj-boeken-maasdam'
      fullPath: '/dj-boeken-maasdam'
      preLoaderRoute: typeof DjBoekenMaasdamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-leiden': {
      id: '/dj-boeken-leiden'
      path: '/dj-boeken-leiden'
      fullPath: '/dj-boeken-leiden'
      preLoaderRoute: typeof DjBoekenLeidenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-leeuwarden': {
      id: '/dj-boeken-leeuwarden'
      path: '/dj-boeken-leeuwarden'
      fullPath: '/dj-boeken-leeuwarden'
      preLoaderRoute: typeof DjBoekenLeeuwardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-leerdam': {
      id: '/dj-boeken-leerdam'
      path: '/dj-boeken-leerdam'
      fullPath: '/dj-boeken-leerdam'
      preLoaderRoute: typeof DjBoekenLeerdamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-klaaswaal': {
      id: '/dj-boeken-klaaswaal'
      path: '/dj-boeken-klaaswaal'
      fullPath: '/dj-boeken-klaaswaal'
      preLoaderRoute: typeof DjBoekenKlaaswaalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-houten': {
      id: '/dj-boeken-houten'
      path: '/dj-boeken-houten'
      fullPath: '/dj-boeken-houten'
      preLoaderRoute: typeof DjBoekenHoutenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-hoeksche-waard': {
      id: '/dj-boeken-hoeksche-waard'
      path: '/dj-boeken-hoeksche-waard'
      fullPath: '/dj-boeken-hoeksche-waard'
      preLoaderRoute: typeof DjBoekenHoekscheWaardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-hilversum': {
      id: '/dj-boeken-hilversum'
      path: '/dj-boeken-hilversum'
      fullPath: '/dj-boeken-hilversum'
      preLoaderRoute: typeof DjBoekenHilversumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-hendrik-ido-ambacht': {
      id: '/dj-boeken-hendrik-ido-ambacht'
      path: '/dj-boeken-hendrik-ido-ambacht'
      fullPath: '/dj-boeken-hendrik-ido-ambacht'
      preLoaderRoute: typeof DjBoekenHendrikIdoAmbachtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-helmond': {
      id: '/dj-boeken-helmond'
      path: '/dj-boeken-helmond'
      fullPath: '/dj-boeken-helmond'
      preLoaderRoute: typeof DjBoekenHelmondRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-heinenoord': {
      id: '/dj-boeken-heinenoord'
      path: '/dj-boeken-heinenoord'
      fullPath: '/dj-boeken-heinenoord'
      preLoaderRoute: typeof DjBoekenHeinenoordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-hardinxveld-giessendam': {
      id: '/dj-boeken-hardinxveld-giessendam'
      path: '/dj-boeken-hardinxveld-giessendam'
      fullPath: '/dj-boeken-hardinxveld-giessendam'
      preLoaderRoute: typeof DjBoekenHardinxveldGiessendamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-haarlem': {
      id: '/dj-boeken-haarlem'
      path: '/dj-boeken-haarlem'
      fullPath: '/dj-boeken-haarlem'
      preLoaderRoute: typeof DjBoekenHaarlemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-groningen': {
      id: '/dj-boeken-groningen'
      path: '/dj-boeken-groningen'
      fullPath: '/dj-boeken-groningen'
      preLoaderRoute: typeof DjBoekenGroningenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-goudswaard': {
      id: '/dj-boeken-goudswaard'
      path: '/dj-boeken-goudswaard'
      fullPath: '/dj-boeken-goudswaard'
      preLoaderRoute: typeof DjBoekenGoudswaardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-gouda': {
      id: '/dj-boeken-gouda'
      path: '/dj-boeken-gouda'
      fullPath: '/dj-boeken-gouda'
      preLoaderRoute: typeof DjBoekenGoudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-gorinchem': {
      id: '/dj-boeken-gorinchem'
      path: '/dj-boeken-gorinchem'
      fullPath: '/dj-boeken-gorinchem'
      preLoaderRoute: typeof DjBoekenGorinchemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-gorcum': {
      id: '/dj-boeken-gorcum'
      path: '/dj-boeken-gorcum'
      fullPath: '/dj-boeken-gorcum'
      preLoaderRoute: typeof DjBoekenGorcumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-geldermalsen': {
      id: '/dj-boeken-geldermalsen'
      path: '/dj-boeken-geldermalsen'
      fullPath: '/dj-boeken-geldermalsen'
      preLoaderRoute: typeof DjBoekenGeldermalsenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-enschede': {
      id: '/dj-boeken-enschede'
      path: '/dj-boeken-enschede'
      fullPath: '/dj-boeken-enschede'
      preLoaderRoute: typeof DjBoekenEnschedeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-eindhoven': {
      id: '/dj-boeken-eindhoven'
      path: '/dj-boeken-eindhoven'
      fullPath: '/dj-boeken-eindhoven'
      preLoaderRoute: typeof DjBoekenEindhovenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-ede': {
      id: '/dj-boeken-ede'
      path: '/dj-boeken-ede'
      fullPath: '/dj-boeken-ede'
      preLoaderRoute: typeof DjBoekenEdeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-dordrecht': {
      id: '/dj-boeken-dordrecht'
      path: '/dj-boeken-dordrecht'
      fullPath: '/dj-boeken-dordrecht'
      preLoaderRoute: typeof DjBoekenDordrechtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-deventer': {
      id: '/dj-boeken-deventer'
      path: '/dj-boeken-deventer'
      fullPath: '/dj-boeken-deventer'
      preLoaderRoute: typeof DjBoekenDeventerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-den-haag': {
      id: '/dj-boeken-den-haag'
      path: '/dj-boeken-den-haag'
      fullPath: '/dj-boeken-den-haag'
      preLoaderRoute: typeof DjBoekenDenHaagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-den-bosch': {
      id: '/dj-boeken-den-bosch'
      path: '/dj-boeken-den-bosch'
      fullPath: '/dj-boeken-den-bosch'
      preLoaderRoute: typeof DjBoekenDenBoschRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-delft': {
      id: '/dj-boeken-delft'
      path: '/dj-boeken-delft'
      fullPath: '/dj-boeken-delft'
      preLoaderRoute: typeof DjBoekenDelftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-culemborg': {
      id: '/dj-boeken-culemborg'
      path: '/dj-boeken-culemborg'
      fullPath: '/dj-boeken-culemborg'
      preLoaderRoute: typeof DjBoekenCulemborgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-cillaarshoek': {
      id: '/dj-boeken-cillaarshoek'
      path: '/dj-boeken-cillaarshoek'
      fullPath: '/dj-boeken-cillaarshoek'
      preLoaderRoute: typeof DjBoekenCillaarshoekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-capelle-aan-den-ijssel': {
      id: '/dj-boeken-capelle-aan-den-ijssel'
      path: '/dj-boeken-capelle-aan-den-ijssel'
      fullPath: '/dj-boeken-capelle-aan-den-ijssel'
      preLoaderRoute: typeof DjBoekenCapelleAanDenIjsselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-buren': {
      id: '/dj-boeken-buren'
      path: '/dj-boeken-buren'
      fullPath: '/dj-boeken-buren'
      preLoaderRoute: typeof DjBoekenBurenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-breda': {
      id: '/dj-boeken-breda'
      path: '/dj-boeken-breda'
      fullPath: '/dj-boeken-breda'
      preLoaderRoute: typeof DjBoekenBredaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-bommelerwaard': {
      id: '/dj-boeken-bommelerwaard'
      path: '/dj-boeken-bommelerwaard'
      fullPath: '/dj-boeken-bommelerwaard'
      preLoaderRoute: typeof DjBoekenBommelerwaardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-betuwe': {
      id: '/dj-boeken-betuwe'
      path: '/dj-boeken-betuwe'
      fullPath: '/dj-boeken-betuwe'
      preLoaderRoute: typeof DjBoekenBetuweRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-barendrecht': {
      id: '/dj-boeken-barendrecht'
      path: '/dj-boeken-barendrecht'
      fullPath: '/dj-boeken-barendrecht'
      preLoaderRoute: typeof DjBoekenBarendrechtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-assen': {
      id: '/dj-boeken-assen'
      path: '/dj-boeken-assen'
      fullPath: '/dj-boeken-assen'
      preLoaderRoute: typeof DjBoekenAssenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-arnhem': {
      id: '/dj-boeken-arnhem'
      path: '/dj-boeken-arnhem'
      fullPath: '/dj-boeken-arnhem'
      preLoaderRoute: typeof DjBoekenArnhemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-apeldoorn': {
      id: '/dj-boeken-apeldoorn'
      path: '/dj-boeken-apeldoorn'
      fullPath: '/dj-boeken-apeldoorn'
      preLoaderRoute: typeof DjBoekenApeldoornRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-amsterdam': {
      id: '/dj-boeken-amsterdam'
      path: '/dj-boeken-amsterdam'
      fullPath: '/dj-boeken-amsterdam'
      preLoaderRoute: typeof DjBoekenAmsterdamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-amstelveen': {
      id: '/dj-boeken-amstelveen'
      path: '/dj-boeken-amstelveen'
      fullPath: '/dj-boeken-amstelveen'
      preLoaderRoute: typeof DjBoekenAmstelveenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-amersfoort': {
      id: '/dj-boeken-amersfoort'
      path: '/dj-boeken-amersfoort'
      fullPath: '/dj-boeken-amersfoort'
      preLoaderRoute: typeof DjBoekenAmersfoortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-alphen-aan-den-rijn': {
      id: '/dj-boeken-alphen-aan-den-rijn'
      path: '/dj-boeken-alphen-aan-den-rijn'
      fullPath: '/dj-boeken-alphen-aan-den-rijn'
      preLoaderRoute: typeof DjBoekenAlphenAanDenRijnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-almere': {
      id: '/dj-boeken-almere'
      path: '/dj-boeken-almere'
      fullPath: '/dj-boeken-almere'
      preLoaderRoute: typeof DjBoekenAlmereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-alkmaar': {
      id: '/dj-boeken-alkmaar'
      path: '/dj-boeken-alkmaar'
      fullPath: '/dj-boeken-alkmaar'
      preLoaderRoute: typeof DjBoekenAlkmaarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-albrandswaard': {
      id: '/dj-boeken-albrandswaard'
      path: '/dj-boeken-albrandswaard'
      fullPath: '/dj-boeken-albrandswaard'
      preLoaderRoute: typeof DjBoekenAlbrandswaardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-boeken-alblasserdam': {
      id: '/dj-boeken-alblasserdam'
      path: '/dj-boeken-alblasserdam'
      fullPath: '/dj-boeken-alblasserdam'
      preLoaderRoute: typeof DjBoekenAlblasserdamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj': {
      id: '/dj'
      path: '/dj'
      fullPath: '/dj'
      preLoaderRoute: typeof DjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bruiloft-dj-tiel': {
      id: '/bruiloft-dj-tiel'
      path: '/bruiloft-dj-tiel'
      fullPath: '/bruiloft-dj-tiel'
      preLoaderRoute: typeof BruiloftDjTielRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bruiloft-dj-rotterdam': {
      id: '/bruiloft-dj-rotterdam'
      path: '/bruiloft-dj-rotterdam'
      fullPath: '/bruiloft-dj-rotterdam'
      preLoaderRoute: typeof BruiloftDjRotterdamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bruiloft-dj-hoeksche-waard': {
      id: '/bruiloft-dj-hoeksche-waard'
      path: '/bruiloft-dj-hoeksche-waard'
      fullPath: '/bruiloft-dj-hoeksche-waard'
      preLoaderRoute: typeof BruiloftDjHoekscheWaardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bruiloft-dj-dordrecht': {
      id: '/bruiloft-dj-dordrecht'
      path: '/bruiloft-dj-dordrecht'
      fullPath: '/bruiloft-dj-dordrecht'
      preLoaderRoute: typeof BruiloftDjDordrechtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bruiloft-dj-betuwe': {
      id: '/bruiloft-dj-betuwe'
      path: '/bruiloft-dj-betuwe'
      fullPath: '/bruiloft-dj-betuwe'
      preLoaderRoute: typeof BruiloftDjBetuweRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bruiloft-dj': {
      id: '/bruiloft-dj'
      path: '/bruiloft-dj'
      fullPath: '/bruiloft-dj'
      preLoaderRoute: typeof BruiloftDjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biografie': {
      id: '/biografie'
      path: '/biografie'
      fullPath: '/biografie'
      preLoaderRoute: typeof BiografieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artiesten': {
      id: '/artiesten'
      path: '/artiesten'
      fullPath: '/artiesten'
      preLoaderRoute: typeof ArtiestenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algemene-voorwaarden': {
      id: '/algemene-voorwaarden'
      path: '/algemene-voorwaarden'
      fullPath: '/algemene-voorwaarden'
      preLoaderRoute: typeof AlgemeneVoorwaardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlgemeneVoorwaardenRoute: AlgemeneVoorwaardenRoute,
  ArtiestenRoute: ArtiestenRoute,
  BiografieRoute: BiografieRoute,
  BruiloftDjRoute: BruiloftDjRoute,
  BruiloftDjBetuweRoute: BruiloftDjBetuweRoute,
  BruiloftDjDordrechtRoute: BruiloftDjDordrechtRoute,
  BruiloftDjHoekscheWaardRoute: BruiloftDjHoekscheWaardRoute,
  BruiloftDjRotterdamRoute: BruiloftDjRotterdamRoute,
  BruiloftDjTielRoute: BruiloftDjTielRoute,
  ContactRoute: ContactRoute,
  DjRoute: DjRoute,
  DjBoekenAlblasserdamRoute: DjBoekenAlblasserdamRoute,
  DjBoekenAlbrandswaardRoute: DjBoekenAlbrandswaardRoute,
  DjBoekenAlkmaarRoute: DjBoekenAlkmaarRoute,
  DjBoekenAlmereRoute: DjBoekenAlmereRoute,
  DjBoekenAlphenAanDenRijnRoute: DjBoekenAlphenAanDenRijnRoute,
  DjBoekenAmersfoortRoute: DjBoekenAmersfoortRoute,
  DjBoekenAmstelveenRoute: DjBoekenAmstelveenRoute,
  DjBoekenAmsterdamRoute: DjBoekenAmsterdamRoute,
  DjBoekenApeldoornRoute: DjBoekenApeldoornRoute,
  DjBoekenArnhemRoute: DjBoekenArnhemRoute,
  DjBoekenAssenRoute: DjBoekenAssenRoute,
  DjBoekenBarendrechtRoute: DjBoekenBarendrechtRoute,
  DjBoekenBetuweRoute: DjBoekenBetuweRoute,
  DjBoekenBommelerwaardRoute: DjBoekenBommelerwaardRoute,
  DjBoekenBredaRoute: DjBoekenBredaRoute,
  DjBoekenBurenRoute: DjBoekenBurenRoute,
  DjBoekenCapelleAanDenIjsselRoute: DjBoekenCapelleAanDenIjsselRoute,
  DjBoekenCillaarshoekRoute: DjBoekenCillaarshoekRoute,
  DjBoekenCulemborgRoute: DjBoekenCulemborgRoute,
  DjBoekenDelftRoute: DjBoekenDelftRoute,
  DjBoekenDenBoschRoute: DjBoekenDenBoschRoute,
  DjBoekenDenHaagRoute: DjBoekenDenHaagRoute,
  DjBoekenDeventerRoute: DjBoekenDeventerRoute,
  DjBoekenDordrechtRoute: DjBoekenDordrechtRoute,
  DjBoekenEdeRoute: DjBoekenEdeRoute,
  DjBoekenEindhovenRoute: DjBoekenEindhovenRoute,
  DjBoekenEnschedeRoute: DjBoekenEnschedeRoute,
  DjBoekenGeldermalsenRoute: DjBoekenGeldermalsenRoute,
  DjBoekenGorcumRoute: DjBoekenGorcumRoute,
  DjBoekenGorinchemRoute: DjBoekenGorinchemRoute,
  DjBoekenGoudaRoute: DjBoekenGoudaRoute,
  DjBoekenGoudswaardRoute: DjBoekenGoudswaardRoute,
  DjBoekenGroningenRoute: DjBoekenGroningenRoute,
  DjBoekenHaarlemRoute: DjBoekenHaarlemRoute,
  DjBoekenHardinxveldGiessendamRoute: DjBoekenHardinxveldGiessendamRoute,
  DjBoekenHeinenoordRoute: DjBoekenHeinenoordRoute,
  DjBoekenHelmondRoute: DjBoekenHelmondRoute,
  DjBoekenHendrikIdoAmbachtRoute: DjBoekenHendrikIdoAmbachtRoute,
  DjBoekenHilversumRoute: DjBoekenHilversumRoute,
  DjBoekenHoekscheWaardRoute: DjBoekenHoekscheWaardRoute,
  DjBoekenHoutenRoute: DjBoekenHoutenRoute,
  DjBoekenKlaaswaalRoute: DjBoekenKlaaswaalRoute,
  DjBoekenLeerdamRoute: DjBoekenLeerdamRoute,
  DjBoekenLeeuwardenRoute: DjBoekenLeeuwardenRoute,
  DjBoekenLeidenRoute: DjBoekenLeidenRoute,
  DjBoekenMaasdamRoute: DjBoekenMaasdamRoute,
  DjBoekenMaastrichtRoute: DjBoekenMaastrichtRoute,
  DjBoekenMiddelburgRoute: DjBoekenMiddelburgRoute,
  DjBoekenMijnsheerenlandRoute: DjBoekenMijnsheerenlandRoute,
  DjBoekenNieuwBeijerlandRoute: DjBoekenNieuwBeijerlandRoute,
  DjBoekenNieuwegeinRoute: DjBoekenNieuwegeinRoute,
  DjBoekenNijmegenRoute: DjBoekenNijmegenRoute,
  DjBoekenNumansdorpRoute: DjBoekenNumansdorpRoute,
  DjBoekenOphemertRoute: DjBoekenOphemertRoute,
  DjBoekenOssRoute: DjBoekenOssRoute,
  DjBoekenOudBeijerlandRoute: DjBoekenOudBeijerlandRoute,
  DjBoekenPapendrechtRoute: DjBoekenPapendrechtRoute,
  DjBoekenPiershilRoute: DjBoekenPiershilRoute,
  DjBoekenPoortugaalRoute: DjBoekenPoortugaalRoute,
  DjBoekenPuttershoekRoute: DjBoekenPuttershoekRoute,
  DjBoekenRhoonRoute: DjBoekenRhoonRoute,
  DjBoekenRidderkerkRoute: DjBoekenRidderkerkRoute,
  DjBoekenRivierenlandRoute: DjBoekenRivierenlandRoute,
  DjBoekenRoermondRoute: DjBoekenRoermondRoute,
  DjBoekenRotterdamRoute: DjBoekenRotterdamRoute,
  DjBoekenSGravendeelRoute: DjBoekenSGravendeelRoute,
  DjBoekenSchiedamRoute: DjBoekenSchiedamRoute,
  DjBoekenSliedrechtRoute: DjBoekenSliedrechtRoute,
  DjBoekenSpijkenisseRoute: DjBoekenSpijkenisseRoute,
  DjBoekenStrijenRoute: DjBoekenStrijenRoute,
  DjBoekenStrijensasRoute: DjBoekenStrijensasRoute,
  DjBoekenTielRoute: DjBoekenTielRoute,
  DjBoekenTiengemetenRoute: DjBoekenTiengemetenRoute,
  DjBoekenTilburgRoute: DjBoekenTilburgRoute,
  DjBoekenTuilRoute: DjBoekenTuilRoute,
  DjBoekenUtrechtRoute: DjBoekenUtrechtRoute,
  DjBoekenVarikRoute: DjBoekenVarikRoute,
  DjBoekenVeenendaalRoute: DjBoekenVeenendaalRoute,
  DjBoekenVenloRoute: DjBoekenVenloRoute,
  DjBoekenVlaardingenRoute: DjBoekenVlaardingenRoute,
  DjBoekenWageningenRoute: DjBoekenWageningenRoute,
  DjBoekenWestmaasRoute: DjBoekenWestmaasRoute,
  DjBoekenZaltbommelRoute: DjBoekenZaltbommelRoute,
  DjBoekenZeistRoute: DjBoekenZeistRoute,
  DjBoekenZoetermeerRoute: DjBoekenZoetermeerRoute,
  DjBoekenZuidBeijerlandRoute: DjBoekenZuidBeijerlandRoute,
  DjBoekenZuidHollandRoute: DjBoekenZuidHollandRoute,
  DjBoekenZwijndrechtRoute: DjBoekenZwijndrechtRoute,
  DjBoekenZwolleRoute: DjBoekenZwolleRoute,
  DjEnMcRoute: DjEnMcRoute,
  FeestOpLocatieRoute: FeestOpLocatieRoute,
  FestivalDjRoute: FestivalDjRoute,
  HorecaRoute: HorecaRoute,
  PersoneelsfeestDjRoute: PersoneelsfeestDjRoute,
  PrijzenRoute: PrijzenRoute,
  PrivacyRoute: PrivacyRoute,
  RegiosRoute: RegiosRoute,
  ReviewsRoute: ReviewsRoute,
  TuinfeestRoute: TuinfeestRoute,
  VerjaardagDjRoute: VerjaardagDjRoute,
  VerzoekjeRoute: VerzoekjeRoute,
  WerkwijzeRoute: WerkwijzeRoute,
  ZakelijkDjRoute: ZakelijkDjRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
